;************************************************************
;*				INSTITUTO POLITECNICO NACIONAL				*
;*			Unidad Profesional Interdisciplinara De 		*
;*			  Ingenieria Y Tecnologías Avanzadas			*
;*															*
;*															*
;*			Programacion De Sistemas En Tiempo Real			*
;*															*
;*		Fecha: 15 de abril del 2018							*	
;*															*
;*		Ramírez López Jesús Alberto							*
;*		Zoza Tejeda Nicole Denisse							*
;*		Becerril Ortega Saul								*
;*															*
;*		PROGRAMA:METRONOMO									*
;*		PARA: MICROCONTROLADOR PIC16F887					*
;*		ENSAMBLADO EN: MPLAB For Windows					*
;************************************************************
			PROCESSOR 16F887
			INCLUDE <P16F887.inc>
			__CONFIG 0X2007,0X2BE2
			__CONFIG 0X2008,0X3FFF

;******************************************************************
;			CONFIGURACION DE PUERTOS
;******************************************************************
			ORG 	0X00
			CLRF	PORTA
			CLRF	PORTB
			CLRF	PORTC		
			CLRF	PORTD	
			BSF		STATUS,RP0	;BANCO1
			CLRF	TRISC
			CLRF	TRISB
			BSF		STATUS,RP1	;BANCO3
			CLRF	ANSEL
			CLRF	ANSELH	
			BCF		STATUS,RP1
			BCF		STATUS,RP0	;BANCO0
;****************************************************************0000 0011		0000 00

INICIO		MOVF	PORTD,W		;LARGO
			ANDLW	0X77
			XORLW	0X00
			BTFSC	STATUS,Z
			GOTO	LARGO_0
			MOVF	PORTD,W
			ANDLW	0X77
			XORLW	0X01
			BTFSC	STATUS,Z
			GOTO	LARGO_2
			MOVF	PORTD,W
			ANDLW	0X77
			XORLW	0X02
			BTFSC	STATUS,Z
			GOTO	LARGO_3
			MOVF	PORTD,W
			ANDLW	0X77
			XORLW	0X03
			BTFSC	STATUS,Z
			GOTO	LARGO_4
			MOVF	PORTD,W
			ANDLW	0X77
			XORLW	0X04
			BTFSC	STATUS,Z
			GOTO	LARGO_5
			MOVF	PORTD,W
			ANDLW	0X77
			XORLW	0X05
			BTFSC	STATUS,Z
			GOTO	LARGO_6
			MOVF	PORTD,W
			ANDLW	0X77
			XORLW	0X06
			BTFSC	STATUS,Z
			GOTO	LARGO_7
			MOVF	PORTD,W
			ANDLW	0X77
			XORLW	0X07
			BTFSC	STATUS,Z
			GOTO	LARGO_8
			
			MOVF	PORTD,W		;LARGHETTO
			ANDLW	0X77
			XORLW	0X10
			BTFSC	STATUS,Z
			GOTO	LARGHETTO_0
			MOVF	PORTD,W
			ANDLW	0X77
			XORLW	0X11
			BTFSC	STATUS,Z
			GOTO	LARGHETTO_2
			MOVF	PORTD,W
			ANDLW	0X77
			XORLW	0X12
			BTFSC	STATUS,Z
			GOTO	LARGHETTO_3
			MOVF	PORTD,W
			ANDLW	0X77
			XORLW	0X13
			BTFSC	STATUS,Z
			GOTO	LARGHETTO_4
			MOVF	PORTD,W
			ANDLW	0X77
			XORLW	0X14
			BTFSC	STATUS,Z
			GOTO	LARGHETTO_5
			MOVF	PORTD,W
			ANDLW	0X77
			XORLW	0X15
			BTFSC	STATUS,Z
			GOTO	LARGHETTO_6
			MOVF	PORTD,W
			ANDLW	0X77
			XORLW	0X16
			BTFSC	STATUS,Z
			GOTO	LARGHETTO_7
			MOVF	PORTD,W
			ANDLW	0X77
			XORLW	0X17
			BTFSC	STATUS,Z
			GOTO	LARGHETTO_8
			
			MOVF	PORTD,W		;ADAGIO
			ANDLW	0X77
			XORLW	0X20
			BTFSC	STATUS,Z
			GOTO	ADAGIO_0
			MOVF	PORTD,W
			ANDLW	0X77
			XORLW	0X21
			BTFSC	STATUS,Z
			GOTO	ADAGIO_2
			MOVF	PORTD,W
			ANDLW	0X77
			XORLW	0X22
			BTFSC	STATUS,Z
			GOTO	ADAGIO_3
			MOVF	PORTD,W
			ANDLW	0X77
			XORLW	0X23
			BTFSC	STATUS,Z
			GOTO	ADAGIO_4
			MOVF	PORTD,W
			ANDLW	0X77
			XORLW	0X24
			BTFSC	STATUS,Z
			GOTO	ADAGIO_5
			MOVF	PORTD,W
			ANDLW	0X77
			XORLW	0X25
			BTFSC	STATUS,Z
			GOTO	ADAGIO_6
			MOVF	PORTD,W
			ANDLW	0X77
			XORLW	0X26
			BTFSC	STATUS,Z
			GOTO	ADAGIO_7
			MOVF	PORTD,W
			ANDLW	0X77
			XORLW	0X27
			BTFSC	STATUS,Z
			GOTO	ADAGIO_8

			MOVF	PORTD,W		;ANDANTE
			ANDLW	0X77
			XORLW	0X30
			BTFSC	STATUS,Z
			GOTO	ANDANTE_0
			MOVF	PORTD,W
			ANDLW	0X77
			XORLW	0X31
			BTFSC	STATUS,Z
			GOTO	ANDANTE_2
			MOVF	PORTD,W
			ANDLW	0X77
			XORLW	0X32
			BTFSC	STATUS,Z
			GOTO	ANDANTE_3
			MOVF	PORTD,W
			ANDLW	0X77
			XORLW	0X33
			BTFSC	STATUS,Z
			GOTO	ANDANTE_4
			MOVF	PORTD,W
			ANDLW	0X77
			XORLW	0X34
			BTFSC	STATUS,Z
			GOTO	ANDANTE_5
			MOVF	PORTD,W
			ANDLW	0X77
			XORLW	0X35
			BTFSC	STATUS,Z
			GOTO	ANDANTE_6
			MOVF	PORTD,W
			ANDLW	0X77
			XORLW	0X36
			BTFSC	STATUS,Z
			GOTO	ANDANTE_7
			MOVF	PORTD,W
			ANDLW	0X77
			XORLW	0X37
			BTFSC	STATUS,Z
			GOTO	ANDANTE_8

			MOVF	PORTD,W		;MODERATO
			ANDLW	0X77
			XORLW	0X40
			BTFSC	STATUS,Z
			GOTO	MODERATO_0
			MOVF	PORTD,W
			ANDLW	0X77
			XORLW	0X41
			BTFSC	STATUS,Z
			GOTO	MODERATO_2
			MOVF	PORTD,W
			ANDLW	0X77
			XORLW	0X42
			BTFSC	STATUS,Z
			GOTO	MODERATO_3
			MOVF	PORTD,W
			ANDLW	0X77
			XORLW	0X43
			BTFSC	STATUS,Z
			GOTO	MODERATO_4
			MOVF	PORTD,W
			ANDLW	0X77
			XORLW	0X44
			BTFSC	STATUS,Z
			GOTO	MODERATO_5
			MOVF	PORTD,W
			ANDLW	0X77
			XORLW	0X45
			BTFSC	STATUS,Z
			GOTO	MODERATO_6
			MOVF	PORTD,W
			ANDLW	0X77
			XORLW	0X46
			BTFSC	STATUS,Z
			GOTO	MODERATO_7
			MOVF	PORTD,W
			ANDLW	0X77
			XORLW	0X47
			BTFSC	STATUS,Z
			GOTO	MODERATO_8

			MOVF	PORTD,W		;ALLEGRO
			ANDLW	0X77
			XORLW	0X50
			BTFSC	STATUS,Z
			GOTO	ALLEGRO_0
			MOVF	PORTD,W
			ANDLW	0X77
			XORLW	0X51
			BTFSC	STATUS,Z
			GOTO	ALLEGRO_2
			MOVF	PORTD,W
			ANDLW	0X77
			XORLW	0X52
			BTFSC	STATUS,Z
			GOTO	ALLEGRO_3
			MOVF	PORTD,W
			ANDLW	0X77
			XORLW	0X53
			BTFSC	STATUS,Z
			GOTO	ALLEGRO_4
			MOVF	PORTD,W
			ANDLW	0X77
			XORLW	0X54
			BTFSC	STATUS,Z
			GOTO	ALLEGRO_5
			MOVF	PORTD,W
			ANDLW	0X77
			XORLW	0X55
			BTFSC	STATUS,Z
			GOTO	ALLEGRO_6
			MOVF	PORTD,W
			ANDLW	0X77
			XORLW	0X56
			BTFSC	STATUS,Z
			GOTO	ALLEGRO_7
			MOVF	PORTD,W
			ANDLW	0X77
			XORLW	0X57
			BTFSC	STATUS,Z
			GOTO	ALLEGRO_8

			MOVF	PORTD,W		;PRESTO
			ANDLW	0X70
			XORLW	0X60
			BTFSC	STATUS,Z
			GOTO	PRESTO

			MOVF	PORTD,W		;PRESTISSIMO
			ANDLW	0X70
			XORLW	0X70
			BTFSC	STATUS,Z
			GOTO	PRESTISSIMO
			GOTO	INICIO
			
			
;***********************(BPM)************************************

LARGHETTO_0	BSF		PORTB,.4	;LARGHETTO
			BSF		PORTB,.5
			CALL	_20MS
			BCF		PORTB,.4
			BCF		PORTB,.5
			MOVLW	.3
			MOVWF	0X64
			MOVLW	.222
			MOVWF	0X65
			MOVLW	.247
			MOVWF	0X66
			CALL	ST3V			
			GOTO	LARGHETTO_0

LARGHETTO_2	BSF		PORTB,.4	
			BSF		PORTB,.5
			CALL	_20MS
			BCF		PORTB,.4
			BCF		PORTB,.5
			MOVLW	.201
			MOVWF	0X64
			MOVLW	.2
			MOVWF	0X65
			MOVLW	.149
			MOVWF	0X66
			CALL	ST3V
			BSF		PORTB,.6
			BSF		PORTB,.7
			CALL	_10MS
			BCF		PORTB,.6
			BCF		PORTB,.7
			MOVLW	.201
			MOVWF	0X64
			MOVLW	.2
			MOVWF	0X65
			MOVLW	.149
			MOVWF	0X66
			CALL	ST3V
			CALL	_10MS
			GOTO	LARGHETTO_2

LARGHETTO_3	BSF		PORTB,.4	
			BSF		PORTB,.5
			CALL	_20MS
			BCF		PORTB,.4
			BCF		PORTB,.5
			CALL	TLO_3
			MOVLW	.2
			MOVWF	0X20
			BSF		PORTB,.6
			BSF		PORTB,.7
			CALL	_10MS
			BCF		PORTB,.6
			BCF		PORTB,.7
			CALL	TLO_3
			CALL	_10MS
			DECFSZ	0X20,F
			GOTO	$-8
			GOTO	LARGHETTO_3

LARGHETTO_4	BSF		PORTB,.4	
			BSF		PORTB,.5
			CALL	_20MS
			BCF		PORTB,.4
			BCF		PORTB,.5
			CALL	TLO_4
			MOVLW	.3
			MOVWF	0X20
			BSF		PORTB,.6
			BSF		PORTB,.7
			CALL	_10MS
			BCF		PORTB,.6
			BCF		PORTB,.7
			CALL	TLO_4
			CALL	_10MS
			DECFSZ	0X20,F
			GOTO	$-8
			GOTO	LARGHETTO_4

LARGHETTO_5	BSF		PORTB,.4	
			BSF		PORTB,.5
			CALL	_20MS
			BCF		PORTB,.4
			BCF		PORTB,.5
			CALL	TLO_5
			MOVLW	.4
			MOVWF	0X20
			BSF		PORTB,.6
			BSF		PORTB,.7
			CALL	_10MS
			BCF		PORTB,.6
			BCF		PORTB,.7
			CALL	TLO_5
			CALL	_10MS
			DECFSZ	0X20,F
			GOTO	$-8
			GOTO	LARGHETTO_5
LARGHETTO_6	BSF		PORTB,.4	
			BSF		PORTB,.5
			CALL	_20MS
			BCF		PORTB,.4
			BCF		PORTB,.5
			CALL	TLO_6
			MOVLW	.5
			MOVWF	0X20
			BSF		PORTB,.6
			BSF		PORTB,.7
			CALL	_10MS
			BCF		PORTB,.6
			BCF		PORTB,.7
			CALL	TLO_6
			CALL	_10MS
			DECFSZ	0X20,F
			GOTO	$-8	
			GOTO	LARGHETTO_6

LARGHETTO_7	BSF		PORTB,.4	
			BSF		PORTB,.5
			CALL	_20MS
			BCF		PORTB,.4
			BCF		PORTB,.5
			CALL	TLO_7
			MOVLW	.6
			MOVWF	0X20
			BSF		PORTB,.6
			BSF		PORTB,.7
			CALL	_10MS
			BCF		PORTB,.6
			BCF		PORTB,.7
			CALL	TLO_7
			CALL	_10MS
			DECFSZ	0X20,F
			GOTO	$-8
			GOTO	LARGHETTO_7

LARGHETTO_8	BSF		PORTB,.4	
			BSF		PORTB,.5
			CALL	_20MS
			BCF		PORTB,.4
			BCF		PORTB,.5
			CALL	TLO_8
			MOVLW	.7
			MOVWF	0X20
			BSF		PORTB,.6
			BSF		PORTB,.7
			CALL	_10MS
			BCF		PORTB,.6
			BCF		PORTB,.7
			CALL	TLO_8
			CALL	_10MS
			DECFSZ	0X20,F
			GOTO	$-8
			GOTO	LARGHETTO_8
	;LARGO
LARGO_0		BSF		PORTB,.4	
			BSF		PORTB,.5
			CALL	_20MS
			BCF		PORTB,.4
			BCF		PORTB,.5
			MOVLW	.132
			MOVWF	0X64
			MOVLW	.12
			MOVWF	0X65
			MOVLW	.155
			MOVWF	0X66
			CALL	ST3V
			GOTO	LARGO_0

LARGO_2		BSF		PORTB,.4	
			BSF		PORTB,.5
			CALL	_20MS
			BCF		PORTB,.4
			BCF		PORTB,.5
			MOVLW	.45
			MOVWF	0X64
			MOVLW	.153
			MOVWF	0X65
			MOVLW	.17
			MOVWF	0X66
			CALL	ST3V
			NOP
			BSF		PORTB,.6
			BSF		PORTB,.7
			CALL	_10MS
			BCF		PORTB,.6
			BCF		PORTB,.7
			MOVLW	.45
			MOVWF	0X64
			MOVLW	.153
			MOVWF	0X65
			MOVLW	.17
			MOVWF	0X66
			CALL	ST3V
			NOP
			CALL	_10MS				
			GOTO	LARGO_2

LARGO_3		BSF		PORTB,.4	
			BSF		PORTB,.5
			CALL	_20MS
			BCF		PORTB,.4
			BCF		PORTB,.5
			CALL	TLA_3
			MOVLW	.2
			MOVWF	0X20
			BSF		PORTB,.6
			BSF		PORTB,.7
			CALL	_10MS
			BCF		PORTB,.6
			BCF		PORTB,.7
			CALL	TLA_3
			CALL	_10MS
			DECFSZ	0X20,F
			GOTO	$-8			
			GOTO	LARGO_3
LARGO_4		BSF		PORTB,.4	
			BSF		PORTB,.5
			CALL	_20MS
			BCF		PORTB,.4
			BCF		PORTB,.5
			CALL	TLA_4
			MOVLW	.3
			MOVWF	0X20
			BSF		PORTB,.6
			BSF		PORTB,.7
			CALL	_10MS
			BCF		PORTB,.6
			BCF		PORTB,.7
			CALL	TLA_4
			CALL	_10MS
			DECFSZ	0X20,F
			GOTO	$-8			
			GOTO	LARGO_4
LARGO_5		BSF		PORTB,.4	
			BSF		PORTB,.5
			CALL	_20MS
			BCF		PORTB,.4
			BCF		PORTB,.5
			CALL	TLA_5
			MOVLW	.4
			MOVWF	0X20
			BSF		PORTB,.6
			BSF		PORTB,.7
			CALL	_10MS
			BCF		PORTB,.6
			BCF		PORTB,.7
			CALL	TLA_5
			CALL	_10MS
			DECFSZ	0X20,F
			GOTO	$-8				
			GOTO	LARGO_5
LARGO_6		BSF		PORTB,.4	
			BSF		PORTB,.5
			CALL	_20MS
			BCF		PORTB,.4
			BCF		PORTB,.5
			CALL	TLA_6
			MOVLW	.5
			MOVWF	0X20
			BSF		PORTB,.6
			BSF		PORTB,.7
			CALL	_10MS
			BCF		PORTB,.6
			BCF		PORTB,.7
			CALL	TLA_6
			CALL	_10MS
			DECFSZ	0X20,F
			GOTO	$-8			
			GOTO	LARGO_6
LARGO_7		BSF		PORTB,.4	
			BSF		PORTB,.5
			CALL	_20MS
			BCF		PORTB,.4
			BCF		PORTB,.5
			CALL	TLA_7
			MOVLW	.6
			MOVWF	0X20
			BSF		PORTB,.6
			BSF		PORTB,.7
			CALL	_10MS
			BCF		PORTB,.6
			BCF		PORTB,.7
			CALL	TLA_7
			CALL	_10MS
			DECFSZ	0X20,F
			GOTO	$-8		
			GOTO	LARGO_7
LARGO_8		BSF		PORTB,.4	
			BSF		PORTB,.5
			CALL	_20MS
			BCF		PORTB,.4
			BCF		PORTB,.5
			CALL	TLA_8
			MOVLW	.7
			MOVWF	0X20
			BSF		PORTB,.6
			BSF		PORTB,.7
			CALL	_10MS
			BCF		PORTB,.6
			BCF		PORTB,.7
			CALL	TLA_8
			CALL	_10MS
			DECFSZ	0X20,F
			GOTO	$-8			
			GOTO	LARGO_8
;ADAGIO

ADAGIO_0 	BSF		PORTB,.4	
			BSF		PORTB,.5
			CALL	_20MS
			BCF		PORTB,.4
			BCF		PORTB,.5
			MOVLW	.186
			MOVWF	0X64
			MOVLW	.6
			MOVWF	0X65
			MOVLW	.132
			MOVWF	0X66
			CALL	ST3V
			NOP
			GOTO	ADAGIO_0

ADAGIO_2	BSF		PORTB,.4	
			BSF		PORTB,.5
			CALL	_20MS
			BCF		PORTB,.4
			BCF		PORTB,.5
			MOVLW	.58
			MOVWF	0X64
			MOVLW	.144
			MOVWF	0X65
			MOVLW	.8
			MOVWF	0X66
			CALL	ST3V
			BSF		PORTB,.6
			BSF		PORTB,.7
			CALL	_10MS
			BCF		PORTB,.6
			BCF		PORTB,.7
			MOVLW	.58
			MOVWF	0X64
			MOVLW	.144
			MOVWF	0X65
			MOVLW	.8
			MOVWF	0X66
			CALL	ST3V
			CALL	_10MS				
			GOTO	ADAGIO_2

ADAGIO_3	BSF		PORTB,.4	
			BSF		PORTB,.5
			CALL	_20MS
			BCF		PORTB,.4
			BCF		PORTB,.5
			CALL	AN_3
			MOVLW	.2
			MOVWF	0X20
			BSF		PORTB,.6
			BSF		PORTB,.7
			CALL	_10MS
			BCF		PORTB,.6
			BCF		PORTB,.7
			CALL	AN_3
			CALL	_10MS
			DECFSZ	0X20,F
			GOTO	$-8			
			GOTO    ADAGIO_3

ADAGIO_4	BSF		PORTB,.4	
			BSF		PORTB,.5
			CALL	_20MS
			BCF		PORTB,.4
			BCF		PORTB,.5
			CALL	AN_4
			MOVLW	.3
			MOVWF	0X20
			BSF		PORTB,.6
			BSF		PORTB,.7
			CALL	_10MS
			BCF		PORTB,.6
			BCF		PORTB,.7
			CALL	AN_4
			CALL	_10MS
			DECFSZ	0X20,F
			GOTO	$-8			
			GOTO	ADAGIO_4

ADAGIO_5	BSF		PORTB,.4	
			BSF		PORTB,.5
			CALL	_20MS
			BCF		PORTB,.4
			BCF		PORTB,.5
			CALL	AN_5
			MOVLW	.4
			MOVWF	0X20
			BSF		PORTB,.6
			BSF		PORTB,.7
			CALL	_10MS
			BCF		PORTB,.6
			BCF		PORTB,.7
			CALL	AN_5
			CALL	_10MS
			DECFSZ	0X20,F
			GOTO	$-8				
			GOTO	ADAGIO_5

ADAGIO_6	BSF		PORTB,.4	
			BSF		PORTB,.5
			CALL	_20MS
			BCF		PORTB,.4
			BCF		PORTB,.5
			CALL	AN_6
			MOVLW	.5
			MOVWF	0X20
			BSF		PORTB,.6
			BSF		PORTB,.7
			CALL	_10MS
			BCF		PORTB,.6
			BCF		PORTB,.7
			CALL	AN_6
			CALL	_10MS
			DECFSZ	0X20,F
			GOTO	$-8			
			GOTO	ADAGIO_6

ADAGIO_7	BSF		PORTB,.4	
			BSF		PORTB,.5
			CALL	_20MS
			BCF		PORTB,.4
			BCF		PORTB,.5
			CALL	AN_7
			MOVLW	.6
			MOVWF	0X20
			BSF		PORTB,.6
			BSF		PORTB,.7
			CALL	_10MS
			BCF		PORTB,.6
			BCF		PORTB,.7
			CALL	AN_7
			CALL	_10MS
			DECFSZ	0X20,F
			GOTO	$-8		
			GOTO	ADAGIO_7

ADAGIO_8	BSF		PORTB,.4	
			BSF		PORTB,.5
			CALL	_20MS
			BCF		PORTB,.4
			BCF		PORTB,.5
			CALL	AN_8
			MOVLW	.7
			MOVWF	0X20
			BSF		PORTB,.6
			BSF		PORTB,.7
			CALL	_10MS
			BCF		PORTB,.6
			BCF		PORTB,.7
			CALL	AN_8
			CALL	_10MS
			DECFSZ	0X20,F
			GOTO	$-8			
			GOTO	ADAGIO_8

;ANDANTE

ANDANTE_0 	BSF		PORTB,.4	
			BSF		PORTB,.5
			CALL	_20MS
			BCF		PORTB,.4
			BCF		PORTB,.5
			MOVLW	.18
			MOVWF	0X64
			MOVLW	.156
			MOVWF	0X65
			MOVLW	.45
			MOVWF	0X66
			CALL	ST3V
			GOTO	ANDANTE_0

ANDANTE_2	BSF		PORTB,.4	
			BSF		PORTB,.5
			CALL	_20MS
			BCF		PORTB,.4
			BCF		PORTB,.5
			MOVLW	.126
			MOVWF	0X64
			MOVLW	.3
			MOVWF	0X65
			MOVLW	.135
			MOVWF	0X66
			CALL	ST3V
			NOP
			NOP
			BSF		PORTB,.6
			BSF		PORTB,.7
			CALL	_10MS
			BCF		PORTB,.6
			BCF		PORTB,.7
			MOVLW	.126
			MOVWF	0X64
			MOVLW	.3
			MOVWF	0X65
			MOVLW	.135
			MOVWF	0X66
			CALL	ST3V
			NOP
			NOP
			CALL	_10MS				
			GOTO	ANDANTE_2

ANDANTE_3	BSF		PORTB,.4	
			BSF		PORTB,.5
			CALL	_20MS
			BCF		PORTB,.4
			BCF		PORTB,.5
			CALL	ANT_3
			MOVLW	.2
			MOVWF	0X20
			BSF		PORTB,.6
			BSF		PORTB,.7
			CALL	_10MS
			BCF		PORTB,.6
			BCF		PORTB,.7
			CALL	ANT_3
			CALL	_10MS
			DECFSZ	0X20,F
			GOTO	$-8			
			GOTO    ANDANTE_3

ANDANTE_4	BSF		PORTB,.4	
			BSF		PORTB,.5
			CALL	_20MS
			BCF		PORTB,.4
			BCF		PORTB,.5
			CALL	ANT_4
			MOVLW	.3
			MOVWF	0X20
			BSF		PORTB,.6
			BSF		PORTB,.7
			CALL	_10MS
			BCF		PORTB,.6
			BCF		PORTB,.7
			CALL	ANT_4
			CALL	_10MS
			DECFSZ	0X20,F
			GOTO	$-8			
			GOTO	ANDANTE_4

ANDANTE_5	BSF		PORTB,.4	
			BSF		PORTB,.5
			CALL	_20MS
			BCF		PORTB,.4
			BCF		PORTB,.5
			CALL	ANT_5
			MOVLW	.4
			MOVWF	0X20
			BSF		PORTB,.6
			BSF		PORTB,.7
			CALL	_10MS
			BCF		PORTB,.6
			BCF		PORTB,.7
			CALL	ANT_5
			CALL	_10MS
			DECFSZ	0X20,F
			GOTO	$-8				
			GOTO	ANDANTE_5

ANDANTE_6	BSF		PORTB,.4	
			BSF		PORTB,.5
			CALL	_20MS
			BCF		PORTB,.4
			BCF		PORTB,.5
			CALL	ANT_6
			MOVLW	.5
			MOVWF	0X20
			BSF		PORTB,.6
			BSF		PORTB,.7
			CALL	_10MS
			BCF		PORTB,.6
			BCF		PORTB,.7
			CALL	ANT_6
			CALL	_10MS
			DECFSZ	0X20,F
			GOTO	$-8			
			GOTO	ANDANTE_6

ANDANTE_7	BSF		PORTB,.4	
			BSF		PORTB,.5
			CALL	_20MS
			BCF		PORTB,.4
			BCF		PORTB,.5
			CALL	ANT_7
			MOVLW	.6
			MOVWF	0X20
			BSF		PORTB,.6
			BSF		PORTB,.7
			CALL	_10MS
			BCF		PORTB,.6
			BCF		PORTB,.7
			CALL	ANT_7
			CALL	_10MS
			DECFSZ	0X20,F
			GOTO	$-8		
			GOTO	ANDANTE_7

ANDANTE_8	BSF		PORTB,.4	
			BSF		PORTB,.5
			CALL	_20MS
			BCF		PORTB,.4
			BCF		PORTB,.5
			CALL	ANT_8
			MOVLW	.7
			MOVWF	0X20
			BSF		PORTB,.6
			BSF		PORTB,.7
			CALL	_10MS
			BCF		PORTB,.6
			BCF		PORTB,.7
			CALL	ANT_8
			CALL	_10MS
			DECFSZ	0X20,F
			GOTO	$-8			
			GOTO	ANDANTE_8
;MODERATO
MODERATO_0 	BSF		PORTB,.4	
			BSF		PORTB,.5
			CALL	_20MS
			BCF		PORTB,.4
			BCF		PORTB,.5
			MOVLW	.121
			MOVWF	0X64
			MOVLW	.201
			MOVWF	0X65
			MOVLW	.3
			MOVWF	0X66
			CALL	ST3V
			GOTO	MODERATO_0

MODERATO_2	BSF		PORTB,.4	
			BSF		PORTB,.5
			CALL	_20MS
			BCF		PORTB,.4
			BCF		PORTB,.5
			MOVLW	.28
			MOVWF	0X64
			MOVLW	.43
			MOVWF	0X65
			MOVLW	.35
			MOVWF	0X66
			CALL	ST3V
			BSF		PORTB,.6
			BSF		PORTB,.7
			CALL	_10MS
			BCF		PORTB,.6
			BCF		PORTB,.7
			MOVLW	.28
			MOVWF	0X64
			MOVLW	.43
			MOVWF	0X65
			MOVLW	.35
			MOVWF	0X66
			CALL	ST3V
			CALL	_10MS				
			GOTO	MODERATO_2

MODERATO_3	BSF		PORTB,.4	
			BSF		PORTB,.5
			CALL	_20MS
			BCF		PORTB,.4
			BCF		PORTB,.5
			CALL	MOD_3
			MOVLW	.2
			MOVWF	0X20
			BSF		PORTB,.6
			BSF		PORTB,.7
			CALL	_10MS
			BCF		PORTB,.6
			BCF		PORTB,.7
			CALL	MOD_3
			CALL	_10MS
			DECFSZ	0X20,F
			GOTO	$-8			
			GOTO    MODERATO_3

MODERATO_4	BSF		PORTB,.4	
			BSF		PORTB,.5
			CALL	_20MS
			BCF		PORTB,.4
			BCF		PORTB,.5
			CALL	MOD_4
			MOVLW	.3
			MOVWF	0X20
			BSF		PORTB,.6
			BSF		PORTB,.7
			CALL	_10MS
			BCF		PORTB,.6
			BCF		PORTB,.7
			CALL	MOD_4
			CALL	_10MS
			DECFSZ	0X20,F
			GOTO	$-8			
			GOTO	MODERATO_4

MODERATO_5	BSF		PORTB,.4	
			BSF		PORTB,.5
			CALL	_20MS
			BCF		PORTB,.4
			BCF		PORTB,.5
			CALL	MOD_5
			MOVLW	.4
			MOVWF	0X20
			BSF		PORTB,.6
			BSF		PORTB,.7
			CALL	_10MS
			BCF		PORTB,.6
			BCF		PORTB,.7
			CALL	MOD_5
			CALL	_10MS
			DECFSZ	0X20,F
			GOTO	$-8				
			GOTO	MODERATO_5

MODERATO_6	BSF		PORTB,.4	
			BSF		PORTB,.5
			CALL	_20MS
			BCF		PORTB,.4
			BCF		PORTB,.5
			CALL	MOD_6
			MOVLW	.5
			MOVWF	0X20
			BSF		PORTB,.6
			BSF		PORTB,.7
			CALL	_10MS
			BCF		PORTB,.6
			BCF		PORTB,.7
			CALL	MOD_6
			CALL	_10MS
			DECFSZ	0X20,F
			GOTO	$-8			
			GOTO	MODERATO_6

MODERATO_7	BSF		PORTB,.4	
			BSF		PORTB,.5
			CALL	_20MS
			BCF		PORTB,.4
			BCF		PORTB,.5
			CALL	MOD_7
			MOVLW	.6
			MOVWF	0X20
			BSF		PORTB,.6
			BSF		PORTB,.7
			CALL	_10MS
			BCF		PORTB,.6
			BCF		PORTB,.7
			CALL	MOD_7
			CALL	_10MS
			DECFSZ	0X20,F
			GOTO	$-8		
			GOTO	MODERATO_7

MODERATO_8	BSF		PORTB,.4	
			BSF		PORTB,.5
			CALL	_20MS
			BCF		PORTB,.4
			BCF		PORTB,.5
			CALL	MOD_8
			MOVLW	.7
			MOVWF	0X20
			BSF		PORTB,.6
			BSF		PORTB,.7
			CALL	_10MS
			BCF		PORTB,.6
			BCF		PORTB,.7
			CALL	MOD_8
			CALL	_10MS
			DECFSZ	0X20,F
			GOTO	$-8			
			GOTO	MODERATO_8

;ALLEGRO
ALLEGRO_0 	BSF		PORTB,.4	
			BSF		PORTB,.5
			CALL	_20MS
			BCF		PORTB,.4
			BCF		PORTB,.5
			MOVLW	.201
			MOVWF	0X64
			MOVLW	.149
			MOVWF	0X65
			MOVLW	.2
			MOVWF	0X66
			CALL	ST3V
			GOTO	ALLEGRO_0

ALLEGRO_2	BSF		PORTB,.4	
			BSF		PORTB,.5
			CALL	_20MS
			BCF		PORTB,.4
			BCF		PORTB,.5
			MOVLW	.5
			MOVWF	0X64
			MOVLW	.61
			MOVWF	0X65
			MOVLW	.125
			MOVWF	0X66
			CALL	ST3V
			NOP
			BSF		PORTB,.6
			BSF		PORTB,.7
			CALL	_10MS
			BCF		PORTB,.6
			BCF		PORTB,.7
			MOVLW	.5
			MOVWF	0X64
			MOVLW	.61
			MOVWF	0X65
			MOVLW	.125
			MOVWF	0X66
			CALL	ST3V
			NOP
			CALL	_10MS				
			GOTO	ALLEGRO_2

ALLEGRO_3	BSF		PORTB,.4	
			BSF		PORTB,.5
			CALL	_20MS
			BCF		PORTB,.4
			BCF		PORTB,.5
			CALL	AL_3
			MOVLW	.2
			MOVWF	0X20
			BSF		PORTB,.6
			BSF		PORTB,.7
			CALL	_10MS
			BCF		PORTB,.6
			BCF		PORTB,.7
			CALL	AL_3
			CALL	_10MS
			DECFSZ	0X20,F
			GOTO	$-8			
			GOTO    ALLEGRO_3

ALLEGRO_4	BSF		PORTB,.4	
			BSF		PORTB,.5
			CALL	_20MS
			BCF		PORTB,.4
			BCF		PORTB,.5
			CALL	AL_4
			MOVLW	.3
			MOVWF	0X20
			BSF		PORTB,.6
			BSF		PORTB,.7
			CALL	_10MS
			BCF		PORTB,.6
			BCF		PORTB,.7
			CALL	AL_4
			CALL	_10MS
			DECFSZ	0X20,F
			GOTO	$-8			
			GOTO	ALLEGRO_4

ALLEGRO_5	BSF		PORTB,.4	
			BSF		PORTB,.5
			CALL	_20MS
			BCF		PORTB,.4
			BCF		PORTB,.5
			CALL	AL_5
			MOVLW	.4
			MOVWF	0X20
			BSF		PORTB,.6
			BSF		PORTB,.7
			CALL	_10MS
			BCF		PORTB,.6
			BCF		PORTB,.7
			CALL	AL_5
			CALL	_10MS
			DECFSZ	0X20,F
			GOTO	$-8				
			GOTO	ALLEGRO_5

ALLEGRO_6	BSF		PORTB,.4	
			BSF		PORTB,.5
			CALL	_20MS
			BCF		PORTB,.4
			BCF		PORTB,.5
			CALL	AL_6
			MOVLW	.5
			MOVWF	0X20
			BSF		PORTB,.6
			BSF		PORTB,.7
			CALL	_10MS
			BCF		PORTB,.6
			BCF		PORTB,.7
			CALL	AL_6
			CALL	_10MS
			DECFSZ	0X20,F
			GOTO	$-8			
			GOTO	ALLEGRO_6

ALLEGRO_7	BSF		PORTB,.4	
			BSF		PORTB,.5
			CALL	_20MS
			BCF		PORTB,.4
			BCF		PORTB,.5
			CALL	AL_7
			MOVLW	.6
			MOVWF	0X20
			BSF		PORTB,.6
			BSF		PORTB,.7
			CALL	_10MS
			BCF		PORTB,.6
			BCF		PORTB,.7
			CALL	AL_7
			CALL	_10MS
			DECFSZ	0X20,F
			GOTO	$-8		
			GOTO	ALLEGRO_7

ALLEGRO_8	BSF		PORTB,.4	
			BSF		PORTB,.5
			CALL	_20MS
			BCF		PORTB,.4
			BCF		PORTB,.5
			CALL	AL_8
			MOVLW	.7
			MOVWF	0X20
			BSF		PORTB,.6
			BSF		PORTB,.7
			CALL	_10MS
			BCF		PORTB,.6
			BCF		PORTB,.7
			CALL	AL_8
			CALL	_10MS
			DECFSZ	0X20,F
			GOTO	$-8			
			GOTO	ALLEGRO_8


;PRESTO
PRESTO	 	BSF		PORTB,.4	
			BSF		PORTB,.5
			CALL	_20MS
			BCF		PORTB,.4
			BCF		PORTB,.5
			MOVLW	.178
			MOVWF	0X64
			MOVLW	.189
			MOVWF	0X65
			MOVLW	.1
			MOVWF	0X66
			CALL	ST3V
			NOP
			GOTO	PRESTO

;PRESTISSIMO
PRESTISSIMO	BSF		PORTB,.4	
			BSF		PORTB,.5
			CALL	_20MS
			BCF		PORTB,.4
			BCF		PORTB,.5
			MOVLW	.153
			MOVWF	0X64
			MOVLW	.83
			MOVWF	0X65
			MOVLW	.3
			MOVWF	0X66
			CALL	ST3V
			NOP
			GOTO	PRESTISSIMO


;****************************************************************
TLO_3		MOVLW	.243
			MOVWF	0X61
			MOVLW	.214
			MOVWF	0X62
			CALL	ST2V
			NOP
			NOP
			NOP
			NOP
			RETURN

TLO_4		MOVLW	.222
			MOVWF	0X61
			MOVLW	.172
			MOVWF	0X62
			CALL	ST2V
			RETURN
TLO_5		MOVLW	.151
			MOVWF	0X61
			MOVLW	.198
			MOVWF	0X62
			CALL	ST2V
			RETURN
TLO_6		MOVLW	.135
			MOVWF	0X61
			MOVLW	.139
			MOVWF	0X62
			CALL	ST2V
			NOP
			NOP
			NOP
			NOP
			NOP
			NOP
			RETURN
TLO_7		MOVLW	.135
			MOVWF	0X61
			MOVLW	.151
			MOVWF	0X62
			CALL	ST2V
			RETURN
TLO_8		MOVLW	.193
			MOVWF	0X61
			MOVLW	.90
			MOVWF	0X62
			CALL	ST2V
			RETURN
;LARGO
TLA_3		MOVLW	.13
			MOVWF	0X64
			MOVLW	.97
			MOVWF	0X65
			MOVLW	.63
			MOVWF	0X66
			CALL	ST3V
			NOP
			RETURN

TLA_4		MOVLW	.42
			MOVWF	0X64
			MOVLW	.10
			MOVWF	0X65
			MOVLW	.132
			MOVWF	0X66
			CALL	ST3V
			RETURN

TLA_5		MOVLW	.228
			MOVWF	0X61
			MOVLW	.204
			MOVWF	0X62
			CALL	ST2V
			NOP
			NOP
			NOP
			NOP	
			NOP
			RETURN

TLA_6		MOVLW	.222
			MOVWF	0X61
			MOVLW	.172
			MOVWF	0X62
			CALL	ST2V
			RETURN
TLA_7		MOVLW	.208
			MOVWF	0X61
			MOVLW	.155
			MOVWF	0X62
			CALL	ST2V
			NOP
			NOP
			RETURN
TLA_8		MOVLW	.212
			MOVWF	0X61
			MOVLW	.131
			MOVWF	0X62
			CALL	ST2V
			NOP
			NOP
			NOP
			NOP
			NOP
			NOP
			RETURN

;ADAGIO
AN_3		MOVLW	.159
			MOVWF	0X64
			MOVLW	.111
			MOVWF	0X65
			MOVLW	.2
			MOVWF	0X66
			CALL	ST3V
			NOP
			RETURN

AN_4		MOVLW	.241
			MOVWF	0X64
			MOVLW	.4
			MOVWF	0X65
			MOVLW	.35
			MOVWF	0X66
			CALL	ST3V
			RETURN

AN_5		MOVLW	.12
			MOVWF	0X64
			MOVLW	.10
			MOVWF	0X65
			MOVLW	.224
			MOVWF	0X66
			CALL	ST3V
			RETURN

AN_6		MOVLW	.234
			MOVWF	0X61
			MOVLW	.93
			MOVWF	0X62
			CALL	ST2V
			RETURN
AN_7		MOVLW	.133
			MOVWF	0X61
			MOVLW	.137
			MOVWF	0X62
			CALL	ST2V
			NOP
			RETURN
AN_8		MOVLW	.178
			MOVWF	0X61
			MOVLW	.87
			MOVWF	0X62
			CALL	ST2V
			RETURN
;ANDANTE
ANT_3		MOVLW	.198
			MOVWF	0X64
			MOVLW	.111
			MOVWF	0X65
			MOVLW	.2
			MOVWF	0X66
			CALL	ST3V
			NOP
			NOP
			RETURN

ANT_4		MOVLW	.245
			MOVWF	0X61
			MOVLW	.119
			MOVWF	0X62
			CALL	ST2V
			NOP
			NOP
			NOP
			NOP
			NOP
			NOP
			NOP
			NOP
			RETURN

ANT_5		MOVLW	.180
			MOVWF	0X61
			MOVLW	.127
			MOVWF	0X62
			CALL	ST2V
			NOP
			NOP
			NOP
			RETURN

ANT_6		MOVLW	.76
			MOVWF	0X61
			MOVLW	.244
			MOVWF	0X62
			CALL	ST2V
			RETURN
ANT_7		MOVLW	.104
			MOVWF	0X61
			MOVLW	.148
			MOVWF	0X62
			CALL	ST2V
			NOP
			NOP
			RETURN
ANT_8		MOVLW	.178
			MOVWF	0X61
			MOVLW	.73
			MOVWF	0X62
			CALL	ST2V
			RETURN
;MODERATO
MOD_3		MOVLW	.44
			MOVWF	0X64
			MOVLW	.15
			MOVWF	0X65
			MOVLW	.41
			MOVWF	0X66
			CALL	ST3V
			RETURN

MOD_4		MOVLW	.80
			MOVWF	0X61
			MOVLW	.247
			MOVWF	0X62
			CALL	ST2V
			RETURN

MOD_5		MOVLW	.78
			MOVWF	0X61
			MOVLW	.194
			MOVWF	0X62
			CALL	ST2V
			RETURN

MOD_6		MOVLW	.86
			MOVWF	0X61
			MOVLW	.140
			MOVWF	0X62
			CALL	ST2V
			RETURN
MOD_7		MOVLW	.39
			MOVWF	0X61
			MOVLW	.253
			MOVWF	0X62
			CALL	ST2V
			NOP
			NOP
			RETURN
MOD_8		MOVLW	.231
			MOVWF	0X61
			MOVLW	.35
			MOVWF	0X62
			CALL	ST2V
			RETURN

;ALLEGRO
AL_3		MOVLW	.175
			MOVWF	0X61
			MOVLW	.139
			MOVWF	0X62
			CALL	ST2V
			NOP
			NOP
			NOP
			NOP
			RETURN

AL_4		MOVLW	.193
			MOVWF	0X61
			MOVLW	.90
			MOVWF	0X62
			CALL	ST2V
			RETURN

AL_5		MOVLW	.99
			MOVWF	0X61
			MOVLW	.134
			MOVWF	0X62
			CALL	ST2V
			RETURN

AL_6		MOVLW	.183
			MOVWF	0X61
			MOVLW	.57
			MOVWF	0X62
			CALL	ST2V
			NOP
			NOP
			NOP
			RETURN
AL_7		MOVLW	.123
			MOVWF	0X61
			MOVLW	.69
			MOVWF	0X62
			CALL	ST2V
			NOP
			NOP
			RETURN
AL_8		MOVLW	.188
			MOVWF	0X61
			MOVLW	.37
			MOVWF	0X62
			CALL	ST2V
			RETURN
;++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
_10MS		MOVLW	.22
			MOVWF	0X61
			MOVLW	.75
			MOVWF	0X62
			CALL	ST2V
			NOP
			RETURN
_20MS		MOVLW	.38
			MOVWF	0X61
			MOVLW	.87
			MOVWF	0X62
			CALL	ST2V
			NOP
			RETURN
;-------------------------------------------------------------

REBOTE		MOVLW		.176
			MOVWF		0X61
			MOVLW		.23
			MOVWF		0X62
			CALL		ST2V
			RETURN

			INCLUDE     <SUBS_TIEMPO.ASM>
			END