				PROCESSOR   16F887
				INCLUDE <P16F887.inc>
                __CONFIG    0X2007,0X2BE2
				__CONFIG	0X2008,0X3FFF

				CBLOCK		0X70
				W_R, ST_R,PC_R
				ENDC
      			ORG			0X00
      			GOTO		INICIO
			    ORG			0X04
				INCLUDE		<rescate.asm>
			    GOTO		RSI
				INCLUDE		<SUBS_TIEMPO.ASM>
				INCLUDE		<tablas_1.asm>
;*******************************************************************************************

INICIO    	    MOVLW		0X20
				MOVWF		FSR
				CLRF		0X20
				CLRF 		PORTC      
			    CLRF   		PORTB
				BCF			PIR1,RCIF
			    BSF   		STATUS,RP0  
			 	CLRF		TRISD
				CLRF		TRISB
			    MOVLW   	B'10110011'
			    MOVWF   	TRISC    
			    MOVLW   	B'11001111'
			    MOVWF   	OPTION_REG   
				BSF			STATUS,RP1	
				CLRF		ANSEL
				CLRF		ANSELH	
				BCF			STATUS,RP1
				MOVLW   	b'00100100'   
				MOVWF   	TXSTA     
				MOVLW   	.25
				MOVWF   	SPBRG   
		        BCF   		PIE1,RCIE 
		        BCF   		STATUS,RP0
			    MOVLW   	b'10010000'
			    MOVWF   	RCSTA     
			    BSF   		INTCON,PEIE   
		     	BCF  		INTCON,GIE  
 
INICIAR	  		MOVLW		.63
				CALL		CALCULOREG
				CALL		SERVO7
				BCF			PIR1,RCIF
				BSF			STATUS,RP0
				BSF			PIE1,RCIE
				BCF			STATUS,RP0
				BSF			INTCON,GIE
				CALL 		LCD_INI	
				MOVLW		0X20
				MOVWF		FSR

GUARDA			MOVF		FSR,W
				XORLW		0X25
				BTFSS		STATUS,Z
				GOTO		GUARDA
MOSTRAR			BCF			INTCON,GIE
				MOVF 		0X20,W
				MOVWF		PORTD
				CALL  		MANDAR
				MOVF		0X21,W
				MOVWF		PORTD
				CALL		MANDAR
				MOVF 		0X22,W
				MOVWF		PORTD
				CALL  		MANDAR
				MOVF		0X23,W
				MOVWF		PORTD
				CALL		MANDAR
				MOVF		0X24,W
				MOVWF		PORTD
				CALL		MANDAR

				MOVF		0X20,W
				MOVWF		0X50
				MOVF		0X21,W
				MOVWF		0X51
				CALL 		COORD
				BSF			0X53,.0
				CALL		MOVIMIENTO
				MOVF		0X23,W
				MOVWF		0X50
				MOVF		0X24,W
				MOVWF		0X51
				CALL 		COORD
				BSF			0X53,.1
				CALL		MOVIMIENTO
				GOTO		INICIAR
;000000000000000000000000INTERRUPCION000000000000000000000000000000
RSI  			BTFSS		RCSTA,OERR
				GOTO		$+4
				BCF			RCSTA,CREN
				BSF			RCSTA,CREN
				BCF			RCSTA,OERR
				MOVF		RCREG,W
				MOVWF		INDF
;				BSF			STATUS,RP0
;				BCF			PIE1,RCIE
;				BCF			STATUS,RP0
				MOVF		FSR,W
				CALL		TX_DATO	
				INCF		FSR,F
				BCF			PIR1,RCIF
		      	INCLUDE		<resupera.asm>
;+++++

COORD				
_A				MOVF		0X50,W
				XORLW		'A'
				BTFSS		STATUS,Z
				GOTO		_B
				MOVLW		.0
				GOTO 		FINC
_B				MOVF		0X50,W
				XORLW		'B'
				BTFSS		STATUS,Z
				GOTO		_C
				MOVLW		.8
				GOTO 		FINC
_C				MOVF		0X50,W
				XORLW		'C'
				BTFSS		STATUS,Z
				GOTO		_D
				MOVLW		.16
				GOTO 		FINC
_D				MOVF		0X50,W
				XORLW		'D'
				BTFSS		STATUS,Z
				GOTO		_E
				MOVLW		.24
				GOTO 		FINC
_E				MOVF		0X50,W
				XORLW		'E'
				BTFSS		STATUS,Z
				GOTO		_F
				MOVLW		.32
				GOTO 		FINC
_F				MOVF		0X50,W
				XORLW		'F'
				BTFSS		STATUS,Z
				GOTO		_G
				MOVLW		.40
				GOTO 		FINC
_G				MOVF		0X50,W
				XORLW		'G'
				BTFSS		STATUS,Z
				GOTO		_H
				MOVLW		.48
				GOTO 		FINC
_H				MOVLW		.56

FINC			MOVWF		0X52		

				MOVWF		0X51				
_1				MOVF		0X51,W
				XORLW		'1'
				BTFSS		STATUS,Z
				GOTO		_2
				MOVLW		.1
				GOTO 		FINF
_2				MOVF		0X51,W
				XORLW		'2'
				BTFSS		STATUS,Z
				GOTO		_3
				MOVLW		.2
				GOTO 		FINF
_3				MOVF		0X51,W
				XORLW		'3'
				BTFSS		STATUS,Z
				GOTO		_4
				MOVLW		.16
				GOTO 		FINF
_4				MOVF		0X51,W
				XORLW		'4'
				BTFSS		STATUS,Z
				GOTO		_5
				MOVLW		.24
				GOTO 		FINF
_5				MOVF		0X50,W
				XORLW		'5'
				BTFSS		STATUS,Z
				GOTO		_6
				MOVLW		.32
				GOTO 		FINF
_6				MOVF		0X50,W
				XORLW		'6'
				BTFSS		STATUS,Z
				GOTO		_7
				MOVLW		.40
				GOTO 		FINF
_7				MOVF		0X50,W
				XORLW		'7'
				BTFSS		STATUS,Z
				GOTO		_8
				MOVLW		.48
				GOTO 		FINF
_8				MOVLW		.56
FINF			ADDWF		0X52,F
				RETURN


;********************************************************************************************

TX_DATO		 	BCF   		PIR1,TXIF  
		      	MOVWF   	TXREG      
		      	BSF   		STATUS,RP0
			   	BTFSS 		TXSTA,TRMT  
      			GOTO	   	$-1
      			BCF   		STATUS,RP0
      			RETURN
;----------------------LCD------------------------------------------
LCD_INI			BCF			PORTC,.2
				MOVLW		0X01
				MOVWF		PORTD
				CALL		EJECUTA
				MOVLW		0X0C
				MOVWF		PORTD
				CALL		EJECUTA
				MOVLW		0X3C
				MOVWF		PORTD
				CALL		EJECUTA
				BSF			PORTC,.2
				RETURN
	
EJECUTA			BSF			PORTC,.3
				CALL		TIEMPO
				CALL		TIEMPO
				BCF			PORTC,.3
				CALL		TIEMPO
				RETURN
	
MANDAR			BSF			PORTC,.2
				CALL		EJECUTA
				RETURN
	
NEXT			BCF			PORTC,.2
				MOVLW		0XC0
				MOVWF		PORTD
				CALL		EJECUTA
				RETURN
	
TIEMPO			MOVLW		.10	
				MOVWF		0X61
				MOVLW		.10
				MOVWF		0X62
				CALL		ST2V
				RETURN
T25MS			MOVLW		.44
				MOVWF		0X61
				MOVLW		.94
				MOVWF		0X62
				CALL		ST2V
				RETURN
T1SEG			MOVLW		.123
				MOVWF		0X64
				MOVLW		.5
				MOVWF		0X65
				MOVLW		.239
				MOVWF		0X66
				CALL		ST3V
				RETURN
;/////



;MOVIMIENTO		CLRF		0X57
;				MOVLW		.1
;				MOVWF		0X56	
;OTRA			MOVF		0X52,W
;				XORWF		0X56,W
;				BTFSC		STATUS,Z
;				GOTO		CASILLA
;				INCF		0X57,F
;				INCF		0X56
;				GOTO
;				GOTO		OTRA
;CASILLA			MOVLW		B'00001000'
;				MOVWF		PCLATH
;				MOVF		0X57,W
;				ADDLW		.20
;				MOVWF		PCL
							

MOVIMIENTO		MOVF		0X52,W
				XORLW		.1
				BTFSC		STATUS,Z
				GOTO		CASILLA1
				MOVF		0X52,W
				XORLW		.2
				BTFSC		STATUS,Z
				GOTO		CASILLA2	
				MOVF		0X52,W
				XORLW		.3
				BTFSC		STATUS,Z
				GOTO		CASILLA3
				MOVF		0X52,W
				XORLW		.4
				BTFSC		STATUS,Z
				GOTO		CASILLA4
				MOVF		0X52,W
				XORLW		.5
				BTFSC		STATUS,Z
				GOTO		CASILLA5
				MOVF		0X52,W
				XORLW		.6
				BTFSC		STATUS,Z
				GOTO		CASILLA6
				MOVF		0X52,W
				XORLW		.7
				BTFSC		STATUS,Z
				GOTO		CASILLA7
				MOVF		0X52,W
				XORLW		.8
				BTFSC		STATUS,Z
				GOTO		CASILLA8
				MOVF		0X52,W
				XORLW		.9
				BTFSC		STATUS,Z
				GOTO		CASILLA9
				MOVF		0X52,W
				XORLW		.10
				BTFSC		STATUS,Z
				GOTO		CASILLA10
				MOVF		0X52,W
				XORLW		.11
				BTFSC		STATUS,Z
				GOTO		CASILLA11
				MOVF		0X52,W
				XORLW		.12
				BTFSC		STATUS,Z
				GOTO		CASILLA12
				MOVF		0X52,W
				XORLW		.13
				BTFSC		STATUS,Z
				GOTO		CASILLA13
				MOVF		0X52,W
				XORLW		.14
				BTFSC		STATUS,Z
				GOTO		CASILLA14
				MOVF		0X52,W
				XORLW		.15
				BTFSC		STATUS,Z
				GOTO		CASILLA15
				MOVF		0X52,W
				XORLW		.16
				BTFSC		STATUS,Z
				GOTO		CASILLA16
				MOVF		0X52,W
				XORLW		.17
				BTFSC		STATUS,Z
				GOTO		CASILLA17
				MOVF		0X52,W
				XORLW		.18
				BTFSC		STATUS,Z
				GOTO		CASILLA18
				MOVF		0X52,W
				XORLW		.19
				BTFSC		STATUS,Z
				GOTO		CASILLA19
		BCF			PCLATH,.4
		BSF			PCLATH,.3
				MOVF		0X52,W
				XORLW		.20
				BTFSC		STATUS,Z
				GOTO		CASILLA20
				MOVF		0X52,W
				XORLW		.21
				BTFSC		STATUS,Z
				GOTO		CASILLA21
				MOVF		0X52,W
				XORLW		.22
				BTFSC		STATUS,Z
				GOTO		CASILLA22
				MOVF		0X52,W
				XORLW		.23
				BTFSC		STATUS,Z
				GOTO		CASILLA23
				MOVF		0X52,W
				XORLW		.24
				BTFSC		STATUS,Z
				GOTO		CASILLA24
				MOVF		0X52,W
				XORLW		.25
				BTFSC		STATUS,Z
				GOTO		CASILLA25
				MOVF		0X52,W
				XORLW		.26
				BTFSC		STATUS,Z
				GOTO		CASILLA26
				MOVF		0X52,W
				XORLW		.27
				BTFSC		STATUS,Z
				GOTO		CASILLA27
				MOVF		0X52,W
				XORLW		.28
				BTFSC		STATUS,Z
				GOTO		CASILLA28
				MOVF		0X52,W
				XORLW		.29
				BTFSC		STATUS,Z
				GOTO		CASILLA29
				MOVF		0X52,W
				XORLW		.30
				BTFSC		STATUS,Z
				GOTO		CASILLA30
				MOVF		0X52,W
				XORLW		.31
				BTFSC		STATUS,Z
				GOTO		CASILLA31
				MOVF		0X52,W
				XORLW		.32
				BTFSC		STATUS,Z
				GOTO		CASILLA32
				MOVF		0X52,W
				XORLW		.33
				BTFSC		STATUS,Z
				GOTO		CASILLA33
				MOVF		0X52,W
				XORLW		.34
				BTFSC		STATUS,Z
				GOTO		CASILLA34
				MOVF		0X52,W
				XORLW		.35
				BTFSC		STATUS,Z
				GOTO		CASILLA35
				MOVF		0X52,W
				XORLW		.36
				BTFSC		STATUS,Z
				GOTO		CASILLA36
				MOVF		0X52,W
				XORLW		.37
				BTFSC		STATUS,Z
				GOTO		CASILLA37
				MOVF		0X52,W
				XORLW		.38
				BTFSC		STATUS,Z
				GOTO		CASILLA38
				MOVF		0X52,W
				XORLW		.39
				BTFSC		STATUS,Z
				GOTO		CASILLA39
				MOVF		0X52,W
				XORLW		.40
				BTFSC		STATUS,Z
				GOTO		CASILLA40
				MOVF		0X52,W
				XORLW		.41
				BTFSC		STATUS,Z
				GOTO		CASILLA41
				MOVF		0X52,W
				XORLW		.42
				BTFSC		STATUS,Z
				GOTO		CASILLA42
				MOVF		0X52,W
				XORLW		.43
				BTFSC		STATUS,Z
				GOTO		CASILLA43
				MOVF		0X52,W
				XORLW		.44
				BTFSC		STATUS,Z
				GOTO		CASILLA44
				MOVF		0X52,W
				XORLW		.45
				BTFSC		STATUS,Z
				GOTO		CASILLA45
				MOVF		0X52,W
				XORLW		.46
				BTFSC		STATUS,Z
				GOTO		CASILLA46
				MOVF		0X52,W
				XORLW		.47
				BTFSC		STATUS,Z
				GOTO		CASILLA47
				MOVF		0X52,W
				XORLW		.48
				BTFSC		STATUS,Z
				GOTO		CASILLA48
				MOVF		0X52,W
				XORLW		.49
				BTFSC		STATUS,Z
				GOTO		CASILLA49
				MOVF		0X52,W
				XORLW		.50
				BTFSC		STATUS,Z
				GOTO		CASILLA50
				MOVF		0X52,W
				XORLW		.51
				BTFSC		STATUS,Z
				GOTO		CASILLA51
				MOVF		0X52,W
				XORLW		.52
				BTFSC		STATUS,Z
				GOTO		CASILLA52
				MOVF		0X52,W
				XORLW		.53
				BTFSC		STATUS,Z
				GOTO		CASILLA53
				MOVF		0X52,W
				XORLW		.54
				BTFSC		STATUS,Z
				GOTO		CASILLA54
				MOVF		0X52,W
				XORLW		.55
				BTFSC		STATUS,Z
				GOTO		CASILLA55
				MOVF		0X52,W
				XORLW		.56
				BTFSC		STATUS,Z
				GOTO		CASILLA56
				MOVF		0X52,W
				XORLW		.57
				BTFSC		STATUS,Z
				GOTO		CASILLA57
				MOVF		0X52,W
				XORLW		.58
				BTFSC		STATUS,Z
				GOTO		CASILLA58
				MOVF		0X52,W
				XORLW		.59
				BTFSC		STATUS,Z
				GOTO		CASILLA59
				MOVF		0X52,W
				XORLW		.60
				BTFSC		STATUS,Z
				GOTO		CASILLA60
				MOVF		0X52,W
				XORLW		.61
				BTFSC		STATUS,Z
				GOTO		CASILLA61
				MOVF		0X52,W
				XORLW		.62
				BTFSC		STATUS,Z
				GOTO		CASILLA62
				MOVF		0X52,W
				XORLW		.63
				BTFSC		STATUS,Z
				GOTO		CASILLA63
				GOTO		CASILLA64

CASILLA1		MOVLW		.45
				CALL		CALCULOREG_1
				CALL		SERVO1_1
				MOVLW		.45
				CALL		CALCULOREG_1
				CALL		SERVO2_1
				MOVLW		.45
				CALL		CALCULOREG_1
				CALL		SERVO3_1
				MOVLW		.45
				CALL		CALCULOREG_1
				CALL		SERVO4_1
				MOVLW		.45
				CALL		CALCULOREG_1
				CALL		SERVO5_1
				MOVLW		.45
				CALL		CALCULOREG_1
				CALL		SERVO6_1
				MOVLW		.45
				CALL		CALCULOREG_1
				CALL		SERVO2_1
				BTFSS		0X53,.0
				GOTO		$+5
				MOVLW		.45
				CALL		CALCULOREG_1
				CALL		SERVO7_1
				RETURN		
				MOVLW		.45
				CALL		CALCULOREG_1
				CALL		SERVO7_1
				RETURN

CASILLA2		MOVLW		.45
				CALL		CALCULOREG_1
				CALL		SERVO1_1
				MOVLW		.45
				CALL		CALCULOREG_1
				CALL		SERVO2_1
				MOVLW		.45
				CALL		CALCULOREG_1
				CALL		SERVO3_1
				MOVLW		.45
				CALL		CALCULOREG_1
				CALL		SERVO4_1
				MOVLW		.45
				CALL		CALCULOREG_1
				CALL		SERVO5_1
				MOVLW		.45
				CALL		CALCULOREG_1
				CALL		SERVO6_1
				MOVLW		.45
				CALL		CALCULOREG_1
				CALL		SERVO2_1
				BTFSS		0X53,.0
				GOTO		$+5
				MOVLW		.45
				CALL		CALCULOREG_1
				CALL		SERVO7_1
				RETURN		
				MOVLW		.45
				CALL		CALCULOREG_1
				CALL		SERVO7_1
				RETURN

CASILLA3		MOVLW		.45
				CALL		CALCULOREG_1
				CALL		SERVO1_1
				MOVLW		.45
				CALL		CALCULOREG_1
				CALL		SERVO2_1
				MOVLW		.45
				CALL		CALCULOREG_1
				CALL		SERVO3_1
				MOVLW		.45
				CALL		CALCULOREG_1
				CALL		SERVO4_1
				MOVLW		.45
				CALL		CALCULOREG_1
				CALL		SERVO5_1
				MOVLW		.45
				CALL		CALCULOREG_1
				CALL		SERVO6_1
				MOVLW		.45
				CALL		CALCULOREG_1
				CALL		SERVO2_1
				BTFSS		0X53,.0
				GOTO		$+5
				MOVLW		.45
				CALL		CALCULOREG_1
				CALL		SERVO7_1
				RETURN		
				MOVLW		.45
				CALL		CALCULOREG_1
				CALL		SERVO7_1
				RETURN

CASILLA4		MOVLW		.45
				CALL		CALCULOREG_1
				CALL		SERVO1_1
				MOVLW		.45
				CALL		CALCULOREG_1
				CALL		SERVO2_1
				MOVLW		.45
				CALL		CALCULOREG_1
				CALL		SERVO3_1
				MOVLW		.45
				CALL		CALCULOREG_1
				CALL		SERVO4_1
				MOVLW		.45
				CALL		CALCULOREG_1
				CALL		SERVO5_1
				MOVLW		.45
				CALL		CALCULOREG_1
				CALL		SERVO6_1
				MOVLW		.45
				CALL		CALCULOREG_1
				CALL		SERVO2_1
				BTFSS		0X53,.0
				GOTO		$+5
				MOVLW		.45
				CALL		CALCULOREG_1
				CALL		SERVO7_1
				RETURN		
				MOVLW		.45
				CALL		CALCULOREG_1
				CALL		SERVO7_1
				RETURN

CASILLA5		MOVLW		.45
				CALL		CALCULOREG_1
				CALL		SERVO1_1
				MOVLW		.45
				CALL		CALCULOREG_1
				CALL		SERVO2_1
				MOVLW		.45
				CALL		CALCULOREG_1
				CALL		SERVO3_1
				MOVLW		.45
				CALL		CALCULOREG_1
				CALL		SERVO4_1
				MOVLW		.45
				CALL		CALCULOREG_1
				CALL		SERVO5_1
				MOVLW		.45
				CALL		CALCULOREG_1
				CALL		SERVO6_1
				MOVLW		.45
				CALL		CALCULOREG_1
				CALL		SERVO2_1
				BTFSS		0X53,.0
				GOTO		$+5
				MOVLW		.45
				CALL		CALCULOREG_1
				CALL		SERVO7_1
				RETURN		
				MOVLW		.45
				CALL		CALCULOREG_1
				CALL		SERVO7_1
				RETURN

CASILLA6		MOVLW		.45
				CALL		CALCULOREG_1
				CALL		SERVO1_1
				MOVLW		.45
				CALL		CALCULOREG_1
				CALL		SERVO2_1
				MOVLW		.45
				CALL		CALCULOREG_1
				CALL		SERVO3_1
				MOVLW		.45
				CALL		CALCULOREG_1
				CALL		SERVO4_1
				MOVLW		.45
				CALL		CALCULOREG_1
				CALL		SERVO5_1
				MOVLW		.45
				CALL		CALCULOREG_1
				CALL		SERVO6_1
				MOVLW		.45
				CALL		CALCULOREG_1
				CALL		SERVO2_1
				BTFSS		0X53,.0
				GOTO		$+5
				MOVLW		.45
				CALL		CALCULOREG_1
				CALL		SERVO7_1
				RETURN		
				MOVLW		.45
				CALL		CALCULOREG_1
				CALL		SERVO7_1
				RETURN
CASILLA7		MOVLW		.45
				CALL		CALCULOREG_1
				CALL		SERVO1_1
				MOVLW		.45
				CALL		CALCULOREG_1
				CALL		SERVO2_1
				MOVLW		.45
				CALL		CALCULOREG_1
				CALL		SERVO3_1
				MOVLW		.45
				CALL		CALCULOREG_1
				CALL		SERVO4_1
				MOVLW		.45
				CALL		CALCULOREG_1
				CALL		SERVO5_1
				MOVLW		.45
				CALL		CALCULOREG_1
				CALL		SERVO6_1
				MOVLW		.45
				CALL		CALCULOREG_1
				CALL		SERVO2_1
				BTFSS		0X53,.0
				GOTO		$+5
				MOVLW		.45
				CALL		CALCULOREG_1
				CALL		SERVO7_1
				RETURN		
				MOVLW		.45
				CALL		CALCULOREG_1
				CALL		SERVO7_1
				RETURN
CASILLA8		MOVLW		.45
				CALL		CALCULOREG_1
				CALL		SERVO1_1
				MOVLW		.45
				CALL		CALCULOREG_1
				CALL		SERVO2_1
				MOVLW		.45
				CALL		CALCULOREG_1
				CALL		SERVO3_1
				MOVLW		.45
				CALL		CALCULOREG_1
				CALL		SERVO4_1
				MOVLW		.45
				CALL		CALCULOREG_1
				CALL		SERVO5_1
				MOVLW		.45
				CALL		CALCULOREG_1
				CALL		SERVO6_1
				MOVLW		.45
				CALL		CALCULOREG_1
				CALL		SERVO2_1
				BTFSS		0X53,.0
				GOTO		$+5
				MOVLW		.45
				CALL		CALCULOREG_1
				CALL		SERVO7_1
				RETURN		
				MOVLW		.45
				CALL		CALCULOREG_1
				CALL		SERVO7_1
				RETURN
CASILLA9		MOVLW		.45
				CALL		CALCULOREG_1
				CALL		SERVO1_1
				MOVLW		.45
				CALL		CALCULOREG_1
				CALL		SERVO2_1
				MOVLW		.45
				CALL		CALCULOREG_1
				CALL		SERVO3_1
				MOVLW		.45
				CALL		CALCULOREG_1
				CALL		SERVO4_1
				MOVLW		.45
				CALL		CALCULOREG_1
				CALL		SERVO5_1
				MOVLW		.45
				CALL		CALCULOREG_1
				CALL		SERVO6_1
				MOVLW		.45
				CALL		CALCULOREG_1
				CALL		SERVO2_1
				BTFSS		0X53,.0
				GOTO		$+5
				MOVLW		.45
				CALL		CALCULOREG_1
				CALL		SERVO7_1
				RETURN		
				MOVLW		.45
				CALL		CALCULOREG_1
				CALL		SERVO7_1
				RETURN
CASILLA10		MOVLW		.45
				CALL		CALCULOREG_1
				CALL		SERVO1_1
				MOVLW		.45
				CALL		CALCULOREG_1
				CALL		SERVO2_1
				MOVLW		.45
				CALL		CALCULOREG_1
				CALL		SERVO3_1
				MOVLW		.45
				CALL		CALCULOREG_1
				CALL		SERVO4_1
				MOVLW		.45
				CALL		CALCULOREG_1
				CALL		SERVO5_1
				MOVLW		.45
				CALL		CALCULOREG_1
				CALL		SERVO6_1
				MOVLW		.45
				CALL		CALCULOREG_1
				CALL		SERVO2_1
				BTFSS		0X53,.0
				GOTO		$+5
				MOVLW		.45
				CALL		CALCULOREG_1
				CALL		SERVO7_1
				RETURN		
				MOVLW		.45
				CALL		CALCULOREG_1
				CALL		SERVO7_1
				RETURN
CASILLA11		MOVLW		.45
				CALL		CALCULOREG_1
				CALL		SERVO1_1
				MOVLW		.45
				CALL		CALCULOREG_1
				CALL		SERVO2_1
				MOVLW		.45
				CALL		CALCULOREG_1
				CALL		SERVO3_1
				MOVLW		.45
				CALL		CALCULOREG_1
				CALL		SERVO4_1
				MOVLW		.45
				CALL		CALCULOREG_1
				CALL		SERVO5_1
				MOVLW		.45
				CALL		CALCULOREG_1
				CALL		SERVO6_1
				MOVLW		.45
				CALL		CALCULOREG_1
				CALL		SERVO2_1
				BTFSS		0X53,.0
				GOTO		$+5
				MOVLW		.45
				CALL		CALCULOREG_1
				CALL		SERVO7_1
				RETURN		
				MOVLW		.45
				CALL		CALCULOREG_1
				CALL		SERVO7_1
				RETURN
CASILLA12		MOVLW		.45
				CALL		CALCULOREG_1
				CALL		SERVO1_1
				MOVLW		.45
				CALL		CALCULOREG_1
				CALL		SERVO2_1
				MOVLW		.45
				CALL		CALCULOREG_1
				CALL		SERVO3_1
				MOVLW		.45
				CALL		CALCULOREG_1
				CALL		SERVO4_1
				MOVLW		.45
				CALL		CALCULOREG_1
				CALL		SERVO5_1
				MOVLW		.45
				CALL		CALCULOREG_1
				CALL		SERVO6_1
				MOVLW		.45
				CALL		CALCULOREG_1
				CALL		SERVO2_1
				BTFSS		0X53,.0
				GOTO		$+5
				MOVLW		.45
				CALL		CALCULOREG_1
				CALL		SERVO7_1
				RETURN		
				MOVLW		.45
				CALL		CALCULOREG_1
				CALL		SERVO7_1
				RETURN
CASILLA13		MOVLW		.45
				CALL		CALCULOREG_1
				CALL		SERVO1_1
				MOVLW		.45
				CALL		CALCULOREG_1
				CALL		SERVO2_1
				MOVLW		.45
				CALL		CALCULOREG_1
				CALL		SERVO3_1
				MOVLW		.45
				CALL		CALCULOREG_1
				CALL		SERVO4_1
				MOVLW		.45
				CALL		CALCULOREG_1
				CALL		SERVO5_1
				MOVLW		.45
				CALL		CALCULOREG_1
				CALL		SERVO6_1
				MOVLW		.45
				CALL		CALCULOREG_1
				CALL		SERVO2_1
				BTFSS		0X53,.0
				GOTO		$+5
				MOVLW		.45
				CALL		CALCULOREG_1
				CALL		SERVO7_1
				RETURN		
				MOVLW		.45
				CALL		CALCULOREG_1
				CALL		SERVO7_1
				RETURN
CASILLA14		MOVLW		.45
				CALL		CALCULOREG_1
				CALL		SERVO1_1
				MOVLW		.45
				CALL		CALCULOREG_1
				CALL		SERVO2_1
				MOVLW		.45
				CALL		CALCULOREG_1
				CALL		SERVO3_1
				MOVLW		.45
				CALL		CALCULOREG_1
				CALL		SERVO4_1
				MOVLW		.45
				CALL		CALCULOREG_1
				CALL		SERVO5_1
				MOVLW		.45
				CALL		CALCULOREG_1
				CALL		SERVO6_1
				MOVLW		.45
				CALL		CALCULOREG_1
				CALL		SERVO2_1
				BTFSS		0X53,.0
				GOTO		$+5
				MOVLW		.45
				CALL		CALCULOREG_1
				CALL		SERVO7_1
				RETURN		
				MOVLW		.45
				CALL		CALCULOREG_1
				CALL		SERVO7_1
				RETURN
CASILLA15		MOVLW		.45
				CALL		CALCULOREG_1
				CALL		SERVO1_1
				MOVLW		.45
				CALL		CALCULOREG_1
				CALL		SERVO2_1
				MOVLW		.45
				CALL		CALCULOREG_1
				CALL		SERVO3_1
				MOVLW		.45
				CALL		CALCULOREG_1
				CALL		SERVO4_1
				MOVLW		.45
				CALL		CALCULOREG_1
				CALL		SERVO5_1
				MOVLW		.45
				CALL		CALCULOREG_1
				CALL		SERVO6_1
				MOVLW		.45
				CALL		CALCULOREG_1
				CALL		SERVO2_1
				BTFSS		0X53,.0
				GOTO		$+5
				MOVLW		.45
				CALL		CALCULOREG_1
				CALL		SERVO7_1
				RETURN		
				MOVLW		.45
				CALL		CALCULOREG_1
				CALL		SERVO7_1
				RETURN
CASILLA16		MOVLW		.45
				CALL		CALCULOREG_1
				CALL		SERVO1_1
				MOVLW		.45
				CALL		CALCULOREG_1
				CALL		SERVO2_1
				MOVLW		.45
				CALL		CALCULOREG_1
				CALL		SERVO3_1
				MOVLW		.45
				CALL		CALCULOREG_1
				CALL		SERVO4_1
				MOVLW		.45
				CALL		CALCULOREG_1
				CALL		SERVO5_1
				MOVLW		.45
				CALL		CALCULOREG_1
				CALL		SERVO6_1
				MOVLW		.45
				CALL		CALCULOREG_1
				CALL		SERVO2_1
				BTFSS		0X53,.0
				GOTO		$+5
				MOVLW		.45
				CALL		CALCULOREG_1
				CALL		SERVO7_1
				RETURN		
				MOVLW		.45
				CALL		CALCULOREG_1
				CALL		SERVO7_1
				RETURN
CASILLA17		MOVLW		.45
				CALL		CALCULOREG_1
				CALL		SERVO1_1
				MOVLW		.45
				CALL		CALCULOREG_1
				CALL		SERVO2_1
				MOVLW		.45
				CALL		CALCULOREG_1
				CALL		SERVO3_1
				MOVLW		.45
				CALL		CALCULOREG_1
				CALL		SERVO4_1
				MOVLW		.45
				CALL		CALCULOREG_1
				CALL		SERVO5_1
				MOVLW		.45
				CALL		CALCULOREG_1
				CALL		SERVO6_1
				MOVLW		.45
				CALL		CALCULOREG_1
				CALL		SERVO2_1
				BTFSS		0X53,.0
				GOTO		$+5
				MOVLW		.45
				CALL		CALCULOREG_1
				CALL		SERVO7_1
				RETURN		
				MOVLW		.45
				CALL		CALCULOREG_1
				CALL		SERVO7_1
				RETURN
CASILLA18		MOVLW		.45
				CALL		CALCULOREG_1
				CALL		SERVO1_1
				MOVLW		.45
				CALL		CALCULOREG_1
				CALL		SERVO2_1
				MOVLW		.45
				CALL		CALCULOREG_1
				CALL		SERVO3_1
				MOVLW		.45
				CALL		CALCULOREG_1
				CALL		SERVO4_1
				MOVLW		.45
				CALL		CALCULOREG_1
				CALL		SERVO5_1
				MOVLW		.45
				CALL		CALCULOREG_1
				CALL		SERVO6_1
				MOVLW		.45
				CALL		CALCULOREG_1
				CALL		SERVO2_1
				BTFSS		0X53,.0
				GOTO		$+5
				MOVLW		.45
				CALL		CALCULOREG_1
				CALL		SERVO7_1
				RETURN		
				MOVLW		.45
				CALL		CALCULOREG_1
				CALL		SERVO7_1
				RETURN
CASILLA19		MOVLW		.45
				CALL		CALCULOREG_1
				CALL		SERVO1_1
				MOVLW		.45
				CALL		CALCULOREG_1
				CALL		SERVO2_1
				MOVLW		.45
				CALL		CALCULOREG_1
				CALL		SERVO3_1
				MOVLW		.45
				CALL		CALCULOREG_1
				CALL		SERVO4_1
				MOVLW		.45
				CALL		CALCULOREG_1
				CALL		SERVO5_1
				MOVLW		.45
				CALL		CALCULOREG_1
				CALL		SERVO6_1
				MOVLW		.45
				CALL		CALCULOREG_1
				CALL		SERVO2_1
				BTFSS		0X53,.0
				GOTO		$+5
				MOVLW		.45
				CALL		CALCULOREG_1
				CALL		SERVO7_1
				RETURN		
				MOVLW		.45
				CALL		CALCULOREG_1
				CALL		SERVO7_1
				RETURN
;****************************SERVOS************************************************
SERVO1_1		MOVLW		0X21
				MOVWF		0X34
				BSF			PORTB,.0
				CALL		TIEMPOALTO_1
				BCF			PORTB,.0
				CALL		TIEMPOBAJO_1
				DECFSZ		0X30
				GOTO		$-5
				RETURN
SERVO2_1		MOVLW		0X21
				MOVWF		0X34
				BSF			PORTB,.1
				CALL		TIEMPOALTO_1
				BCF			PORTB,.1
				CALL		TIEMPOBAJO_1
				DECFSZ		0X30
				GOTO		$-5
				RETURN
SERVO3_1		MOVLW		0X21
				MOVWF		0X34
				BSF			PORTB,.2
				CALL		TIEMPOALTO_1
				BCF			PORTB,.2
				CALL		TIEMPOBAJO_1
				DECFSZ		0X30
				GOTO		$-5
				RETURN
SERVO4_1		MOVLW		0X21
				MOVWF		0X34
				BSF			PORTB,.3
				CALL		TIEMPOALTO_1
				BCF			PORTB,.3
				CALL		TIEMPOBAJO_1
				DECFSZ		0X30
				GOTO		$-5
				RETURN
SERVO5_1		MOVLW		0X21
				MOVWF		0X34
				BSF			PORTB,.4
				CALL		TIEMPOALTO_1
				BCF			PORTB,.4
				CALL		TIEMPOBAJO_1
				DECFSZ		0X30
				GOTO		$-5
				RETURN
SERVO6_1		MOVLW		0X21
				MOVWF		0X34
				BSF			PORTB,.5
				CALL		TIEMPOALTO_1
				BCF			PORTB,.5
				CALL		TIEMPOBAJO_1
				DECFSZ		0X30
				GOTO		$-5
				RETURN
SERVO7_1		MOVLW		0X21
				MOVWF		0X34
				BSF			PORTB,.6
				CALL		TIEMPOALTO_1
				BCF			PORTB,.6
				CALL		TIEMPOBAJO_1
				DECFSZ		0X30
				GOTO		$-5
				RETURN
CALCULOREG_1	MOVF		0X40,W
				CALL		TABLA_0X30_1
				MOVWF		0X30
				MOVF		0X40,W
				CALL		TABLA_0X31_1
				MOVWF		0X31
				MOVF		0X40,W
				CALL		TABLA_0X32_1
				MOVWF		0X32
				MOVF		0X40,W
				CALL		TABLA_0X33_1
				MOVWF		0X33
				RETURN	

TIEMPOALTO_1	MOVF		0X30,W
				MOVWF		0X61
				MOVF		0X31,W
				MOVWF		0X62
				CALL		ST2V
				RETURN

TIEMPOBAJO_1	MOVF		0X32,W
				MOVWF		0X61
				MOVF		0X33,W
				MOVWF		0X62
				CALL		ST2V
				RETURN
ORG			0X800
CASILLA20		MOVLW		.45
				CALL		CALCULOREG
				CALL		SERVO1
				MOVLW		.45
				CALL		CALCULOREG
				CALL		SERVO2
				MOVLW		.45
				CALL		CALCULOREG
				CALL		SERVO3
				MOVLW		.45
				CALL		CALCULOREG
				CALL		SERVO4
				MOVLW		.45
				CALL		CALCULOREG
				CALL		SERVO5
				MOVLW		.45
				CALL		CALCULOREG
				CALL		SERVO6
				MOVLW		.45
				CALL		CALCULOREG
				CALL		SERVO2
				BTFSS		0X53,.0
				GOTO		$+5
				MOVLW		.45
				CALL		CALCULOREG
				CALL		SERVO7
				CLRF		PCLATH
				RETURN		
				MOVLW		.45
				CALL		CALCULOREG
				CALL		SERVO7
				CLRF		PCLATH
				RETURN
CASILLA21		MOVLW		.45
				CALL		CALCULOREG
				CALL		SERVO1
				MOVLW		.45
				CALL		CALCULOREG
				CALL		SERVO2
				MOVLW		.45
				CALL		CALCULOREG
				CALL		SERVO3
				MOVLW		.45
				CALL		CALCULOREG
				CALL		SERVO4
				MOVLW		.45
				CALL		CALCULOREG
				CALL		SERVO5
				MOVLW		.45
				CALL		CALCULOREG
				CALL		SERVO6
				MOVLW		.45
				CALL		CALCULOREG
				CALL		SERVO2
				BTFSS		0X53,.0
				GOTO		$+5
				MOVLW		.45
				CALL		CALCULOREG
				CALL		SERVO7
				CLRF		PCLATH
				RETURN		
				MOVLW		.45
				CALL		CALCULOREG
				CALL		SERVO7
				CLRF		PCLATH
				RETURN
CASILLA22		MOVLW		.45
				CALL		CALCULOREG
				CALL		SERVO1
				MOVLW		.45
				CALL		CALCULOREG
				CALL		SERVO2
				MOVLW		.45
				CALL		CALCULOREG
				CALL		SERVO3
				MOVLW		.45
				CALL		CALCULOREG
				CALL		SERVO4
				MOVLW		.45
				CALL		CALCULOREG
				CALL		SERVO5
				MOVLW		.45
				CALL		CALCULOREG
				CALL		SERVO6
				MOVLW		.45
				CALL		CALCULOREG
				CALL		SERVO2
				BTFSS		0X53,.0
				GOTO		$+5
				MOVLW		.45
				CALL		CALCULOREG
				CALL		SERVO7
				CLRF		PCLATH
				RETURN		
				MOVLW		.45
				CALL		CALCULOREG
				CALL		SERVO7
				CLRF		PCLATH
				RETURN
CASILLA23		MOVLW		.45
				CALL		CALCULOREG
				CALL		SERVO1
				MOVLW		.45
				CALL		CALCULOREG
				CALL		SERVO2
				MOVLW		.45
				CALL		CALCULOREG
				CALL		SERVO3
				MOVLW		.45
				CALL		CALCULOREG
				CALL		SERVO4
				MOVLW		.45
				CALL		CALCULOREG
				CALL		SERVO5
				MOVLW		.45
				CALL		CALCULOREG
				CALL		SERVO6
				MOVLW		.45
				CALL		CALCULOREG
				CALL		SERVO2
				BTFSS		0X53,.0
				GOTO		$+5
				MOVLW		.45
				CALL		CALCULOREG
				CALL		SERVO7
				CLRF		PCLATH
				RETURN		
				MOVLW		.45
				CALL		CALCULOREG
				CALL		SERVO7
				CLRF		PCLATH
				RETURN
CASILLA24		MOVLW		.45
				CALL		CALCULOREG
				CALL		SERVO1
				MOVLW		.45
				CALL		CALCULOREG
				CALL		SERVO2
				MOVLW		.45
				CALL		CALCULOREG
				CALL		SERVO3
				MOVLW		.45
				CALL		CALCULOREG
				CALL		SERVO4
				MOVLW		.45
				CALL		CALCULOREG
				CALL		SERVO5
				MOVLW		.45
				CALL		CALCULOREG
				CALL		SERVO6
				MOVLW		.45
				CALL		CALCULOREG
				CALL		SERVO2
				BTFSS		0X53,.0
				GOTO		$+5
				MOVLW		.45
				CALL		CALCULOREG
				CALL		SERVO7
				CLRF		PCLATH
				RETURN		
				MOVLW		.45
				CALL		CALCULOREG
				CALL		SERVO7
				CLRF		PCLATH
				RETURN
CASILLA25		MOVLW		.45
				CALL		CALCULOREG
				CALL		SERVO1
				MOVLW		.45
				CALL		CALCULOREG
				CALL		SERVO2
				MOVLW		.45
				CALL		CALCULOREG
				CALL		SERVO3
				MOVLW		.45
				CALL		CALCULOREG
				CALL		SERVO4
				MOVLW		.45
				CALL		CALCULOREG
				CALL		SERVO5
				MOVLW		.45
				CALL		CALCULOREG
				CALL		SERVO6
				MOVLW		.45
				CALL		CALCULOREG
				CALL		SERVO2
				BTFSS		0X53,.0
				GOTO		$+5
				MOVLW		.45
				CALL		CALCULOREG
				CALL		SERVO7
				CLRF		PCLATH
				RETURN		
				MOVLW		.45
				CALL		CALCULOREG
				CALL		SERVO7
				CLRF		PCLATH
				RETURN
CASILLA26		MOVLW		.45
				CALL		CALCULOREG
				CALL		SERVO1
				MOVLW		.45
				CALL		CALCULOREG
				CALL		SERVO2
				MOVLW		.45
				CALL		CALCULOREG
				CALL		SERVO3
				MOVLW		.45
				CALL		CALCULOREG
				CALL		SERVO4
				MOVLW		.45
				CALL		CALCULOREG
				CALL		SERVO5
				MOVLW		.45
				CALL		CALCULOREG
				CALL		SERVO6
				MOVLW		.45
				CALL		CALCULOREG
				CALL		SERVO2
				BTFSS		0X53,.0
				GOTO		$+5
				MOVLW		.45
				CALL		CALCULOREG
				CALL		SERVO7
				CLRF		PCLATH
				RETURN		
				MOVLW		.45
				CALL		CALCULOREG
				CALL		SERVO7
				CLRF		PCLATH
				RETURN
CASILLA27		MOVLW		.45
				CALL		CALCULOREG
				CALL		SERVO1
				MOVLW		.45
				CALL		CALCULOREG
				CALL		SERVO2
				MOVLW		.45
				CALL		CALCULOREG
				CALL		SERVO3
				MOVLW		.45
				CALL		CALCULOREG
				CALL		SERVO4
				MOVLW		.45
				CALL		CALCULOREG
				CALL		SERVO5
				MOVLW		.45
				CALL		CALCULOREG
				CALL		SERVO6
				MOVLW		.45
				CALL		CALCULOREG
				CALL		SERVO2
				BTFSS		0X53,.0
				GOTO		$+5
				MOVLW		.45
				CALL		CALCULOREG
				CALL		SERVO7
				CLRF		PCLATH
				RETURN		
				MOVLW		.45
				CALL		CALCULOREG
				CALL		SERVO7
				CLRF		PCLATH
				RETURN
CASILLA28		MOVLW		.45
				CALL		CALCULOREG
				CALL		SERVO1
				MOVLW		.45
				CALL		CALCULOREG
				CALL		SERVO2
				MOVLW		.45
				CALL		CALCULOREG
				CALL		SERVO3
				MOVLW		.45
				CALL		CALCULOREG
				CALL		SERVO4
				MOVLW		.45
				CALL		CALCULOREG
				CALL		SERVO5
				MOVLW		.45
				CALL		CALCULOREG
				CALL		SERVO6
				MOVLW		.45
				CALL		CALCULOREG
				CALL		SERVO2
				BTFSS		0X53,.0
				GOTO		$+5
				MOVLW		.45
				CALL		CALCULOREG
				CALL		SERVO7
				CLRF		PCLATH
				RETURN		
				MOVLW		.45
				CALL		CALCULOREG
				CALL		SERVO7
				CLRF		PCLATH
				RETURN
CASILLA29		MOVLW		.45
				CALL		CALCULOREG
				CALL		SERVO1
				MOVLW		.45
				CALL		CALCULOREG
				CALL		SERVO2
				MOVLW		.45
				CALL		CALCULOREG
				CALL		SERVO3
				MOVLW		.45
				CALL		CALCULOREG
				CALL		SERVO4
				MOVLW		.45
				CALL		CALCULOREG
				CALL		SERVO5
				MOVLW		.45
				CALL		CALCULOREG
				CALL		SERVO6
				MOVLW		.45
				CALL		CALCULOREG
				CALL		SERVO2
				BTFSS		0X53,.0
				GOTO		$+5
				MOVLW		.45
				CALL		CALCULOREG
				CALL		SERVO7
				CLRF		PCLATH
				RETURN		
				MOVLW		.45
				CALL		CALCULOREG
				CALL		SERVO7
				CLRF		PCLATH
				RETURN
CASILLA30		MOVLW		.45
				CALL		CALCULOREG
				CALL		SERVO1
				MOVLW		.45
				CALL		CALCULOREG
				CALL		SERVO2
				MOVLW		.45
				CALL		CALCULOREG
				CALL		SERVO3
				MOVLW		.45
				CALL		CALCULOREG
				CALL		SERVO4
				MOVLW		.45
				CALL		CALCULOREG
				CALL		SERVO5
				MOVLW		.45
				CALL		CALCULOREG
				CALL		SERVO6
				MOVLW		.45
				CALL		CALCULOREG
				CALL		SERVO2
				BTFSS		0X53,.0
				GOTO		$+5
				MOVLW		.45
				CALL		CALCULOREG
				CALL		SERVO7
				CLRF		PCLATH
				RETURN		
				MOVLW		.45
				CALL		CALCULOREG
				CALL		SERVO7
				CLRF		PCLATH
				RETURN
CASILLA31		MOVLW		.45
				CALL		CALCULOREG
				CALL		SERVO1
				MOVLW		.45
				CALL		CALCULOREG
				CALL		SERVO2
				MOVLW		.45
				CALL		CALCULOREG
				CALL		SERVO3
				MOVLW		.45
				CALL		CALCULOREG
				CALL		SERVO4
				MOVLW		.45
				CALL		CALCULOREG
				CALL		SERVO5
				MOVLW		.45
				CALL		CALCULOREG
				CALL		SERVO6
				MOVLW		.45
				CALL		CALCULOREG
				CALL		SERVO2
				BTFSS		0X53,.0
				GOTO		$+5
				MOVLW		.45
				CALL		CALCULOREG
				CALL		SERVO7
				CLRF		PCLATH
				RETURN		
				MOVLW		.45
				CALL		CALCULOREG
				CALL		SERVO7
				CLRF		PCLATH
				RETURN
CASILLA32		MOVLW		.45
				CALL		CALCULOREG
				CALL		SERVO1
				MOVLW		.45
				CALL		CALCULOREG
				CALL		SERVO2
				MOVLW		.45
				CALL		CALCULOREG
				CALL		SERVO3
				MOVLW		.45
				CALL		CALCULOREG
				CALL		SERVO4
				MOVLW		.45
				CALL		CALCULOREG
				CALL		SERVO5
				MOVLW		.45
				CALL		CALCULOREG
				CALL		SERVO6
				MOVLW		.45
				CALL		CALCULOREG
				CALL		SERVO2
				BTFSS		0X53,.0
				GOTO		$+5
				MOVLW		.45
				CALL		CALCULOREG
				CALL		SERVO7
				CLRF		PCLATH
				RETURN		
				MOVLW		.45
				CALL		CALCULOREG
				CALL		SERVO7
				CLRF		PCLATH
				RETURN
CASILLA33		MOVLW		.45
				CALL		CALCULOREG
				CALL		SERVO1
				MOVLW		.45
				CALL		CALCULOREG
				CALL		SERVO2
				MOVLW		.45
				CALL		CALCULOREG
				CALL		SERVO3
				MOVLW		.45
				CALL		CALCULOREG
				CALL		SERVO4
				MOVLW		.45
				CALL		CALCULOREG
				CALL		SERVO5
				MOVLW		.45
				CALL		CALCULOREG
				CALL		SERVO6
				MOVLW		.45
				CALL		CALCULOREG
				CALL		SERVO2
				BTFSS		0X53,.0
				GOTO		$+5
				MOVLW		.45
				CALL		CALCULOREG
				CALL		SERVO7
				CLRF		PCLATH
				RETURN		
				MOVLW		.45
				CALL		CALCULOREG
				CALL		SERVO7
				CLRF		PCLATH
				RETURN
CASILLA34		MOVLW		.45
				CALL		CALCULOREG
				CALL		SERVO1
				MOVLW		.45
				CALL		CALCULOREG
				CALL		SERVO2
				MOVLW		.45
				CALL		CALCULOREG
				CALL		SERVO3
				MOVLW		.45
				CALL		CALCULOREG
				CALL		SERVO4
				MOVLW		.45
				CALL		CALCULOREG
				CALL		SERVO5
				MOVLW		.45
				CALL		CALCULOREG
				CALL		SERVO6
				MOVLW		.45
				CALL		CALCULOREG
				CALL		SERVO2
				BTFSS		0X53,.0
				GOTO		$+5
				MOVLW		.45
				CALL		CALCULOREG
				CALL		SERVO7
				CLRF		PCLATH
				RETURN		
				MOVLW		.45
				CALL		CALCULOREG
				CALL		SERVO7
				CLRF		PCLATH
				RETURN
CASILLA35		MOVLW		.45
				CALL		CALCULOREG
				CALL		SERVO1
				MOVLW		.45
				CALL		CALCULOREG
				CALL		SERVO2
				MOVLW		.45
				CALL		CALCULOREG
				CALL		SERVO3
				MOVLW		.45
				CALL		CALCULOREG
				CALL		SERVO4
				MOVLW		.45
				CALL		CALCULOREG
				CALL		SERVO5
				MOVLW		.45
				CALL		CALCULOREG
				CALL		SERVO6
				MOVLW		.45
				CALL		CALCULOREG
				CALL		SERVO2
				BTFSS		0X53,.0
				GOTO		$+5
				MOVLW		.45
				CALL		CALCULOREG
				CALL		SERVO7
				CLRF		PCLATH
				RETURN		
				MOVLW		.45
				CALL		CALCULOREG
				CALL		SERVO7
				CLRF		PCLATH
				RETURN
CASILLA36		MOVLW		.45
				CALL		CALCULOREG
				CALL		SERVO1
				MOVLW		.45
				CALL		CALCULOREG
				CALL		SERVO2
				MOVLW		.45
				CALL		CALCULOREG
				CALL		SERVO3
				MOVLW		.45
				CALL		CALCULOREG
				CALL		SERVO4
				MOVLW		.45
				CALL		CALCULOREG
				CALL		SERVO5
				MOVLW		.45
				CALL		CALCULOREG
				CALL		SERVO6
				MOVLW		.45
				CALL		CALCULOREG
				CALL		SERVO2
				BTFSS		0X53,.0
				GOTO		$+5
				MOVLW		.45
				CALL		CALCULOREG
				CALL		SERVO7
				CLRF		PCLATH
				RETURN		
				MOVLW		.45
				CALL		CALCULOREG
				CALL		SERVO7
				CLRF		PCLATH
				RETURN
CASILLA37		MOVLW		.45
				CALL		CALCULOREG
				CALL		SERVO1
				MOVLW		.45
				CALL		CALCULOREG
				CALL		SERVO2
				MOVLW		.45
				CALL		CALCULOREG
				CALL		SERVO3
				MOVLW		.45
				CALL		CALCULOREG
				CALL		SERVO4
				MOVLW		.45
				CALL		CALCULOREG
				CALL		SERVO5
				MOVLW		.45
				CALL		CALCULOREG
				CALL		SERVO6
				MOVLW		.45
				CALL		CALCULOREG
				CALL		SERVO2
				BTFSS		0X53,.0
				GOTO		$+5
				MOVLW		.45
				CALL		CALCULOREG
				CALL		SERVO7
				CLRF		PCLATH
				RETURN		
				MOVLW		.45
				CALL		CALCULOREG
				CALL		SERVO7
				CLRF		PCLATH
				RETURN
CASILLA38		MOVLW		.45
				CALL		CALCULOREG
				CALL		SERVO1
				MOVLW		.45
				CALL		CALCULOREG
				CALL		SERVO2
				MOVLW		.45
				CALL		CALCULOREG
				CALL		SERVO3
				MOVLW		.45
				CALL		CALCULOREG
				CALL		SERVO4
				MOVLW		.45
				CALL		CALCULOREG
				CALL		SERVO5
				MOVLW		.45
				CALL		CALCULOREG
				CALL		SERVO6
				MOVLW		.45
				CALL		CALCULOREG
				CALL		SERVO2
				BTFSS		0X53,.0
				GOTO		$+5
				MOVLW		.45
				CALL		CALCULOREG
				CALL		SERVO7
				CLRF		PCLATH
				RETURN		
				MOVLW		.45
				CALL		CALCULOREG
				CALL		SERVO7
				CLRF		PCLATH
				RETURN
CASILLA39		MOVLW		.45
				CALL		CALCULOREG
				CALL		SERVO1
				MOVLW		.45
				CALL		CALCULOREG
				CALL		SERVO2
				MOVLW		.45
				CALL		CALCULOREG
				CALL		SERVO3
				MOVLW		.45
				CALL		CALCULOREG
				CALL		SERVO4
				MOVLW		.45
				CALL		CALCULOREG
				CALL		SERVO5
				MOVLW		.45
				CALL		CALCULOREG
				CALL		SERVO6
				MOVLW		.45
				CALL		CALCULOREG
				CALL		SERVO2
				BTFSS		0X53,.0
				GOTO		$+5
				MOVLW		.45
				CALL		CALCULOREG
				CALL		SERVO7
				CLRF		PCLATH
				RETURN		
				MOVLW		.45
				CALL		CALCULOREG
				CALL		SERVO7
				CLRF		PCLATH
				RETURN
CASILLA40		MOVLW		.45
				CALL		CALCULOREG
				CALL		SERVO1
				MOVLW		.45
				CALL		CALCULOREG
				CALL		SERVO2
				MOVLW		.45
				CALL		CALCULOREG
				CALL		SERVO3
				MOVLW		.45
				CALL		CALCULOREG
				CALL		SERVO4
				MOVLW		.45
				CALL		CALCULOREG
				CALL		SERVO5
				MOVLW		.45
				CALL		CALCULOREG
				CALL		SERVO6
				MOVLW		.45
				CALL		CALCULOREG
				CALL		SERVO2
				BTFSS		0X53,.0
				GOTO		$+5
				MOVLW		.45
				CALL		CALCULOREG
				CALL		SERVO7
				CLRF		PCLATH
				RETURN		
				MOVLW		.45
				CALL		CALCULOREG
				CALL		SERVO7
				CLRF		PCLATH
				RETURN
CASILLA41		MOVLW		.45
				CALL		CALCULOREG
				CALL		SERVO1
				MOVLW		.45
				CALL		CALCULOREG
				CALL		SERVO2
				MOVLW		.45
				CALL		CALCULOREG
				CALL		SERVO3
				MOVLW		.45
				CALL		CALCULOREG
				CALL		SERVO4
				MOVLW		.45
				CALL		CALCULOREG
				CALL		SERVO5
				MOVLW		.45
				CALL		CALCULOREG
				CALL		SERVO6
				MOVLW		.45
				CALL		CALCULOREG
				CALL		SERVO2
				BTFSS		0X53,.0
				GOTO		$+5
				MOVLW		.45
				CALL		CALCULOREG
				CALL		SERVO7
				CLRF		PCLATH
				RETURN		
				MOVLW		.45
				CALL		CALCULOREG
				CALL		SERVO7
				CLRF		PCLATH
				RETURN
CASILLA42		MOVLW		.45
				CALL		CALCULOREG
				CALL		SERVO1
				MOVLW		.45
				CALL		CALCULOREG
				CALL		SERVO2
				MOVLW		.45
				CALL		CALCULOREG
				CALL		SERVO3
				MOVLW		.45
				CALL		CALCULOREG
				CALL		SERVO4
				MOVLW		.45
				CALL		CALCULOREG
				CALL		SERVO5
				MOVLW		.45
				CALL		CALCULOREG
				CALL		SERVO6
				MOVLW		.45
				CALL		CALCULOREG
				CALL		SERVO2
				BTFSS		0X53,.0
				GOTO		$+5
				MOVLW		.45
				CALL		CALCULOREG
				CALL		SERVO7
				CLRF		PCLATH
				RETURN		
				MOVLW		.45
				CALL		CALCULOREG
				CALL		SERVO7
				CLRF		PCLATH
				RETURN
CASILLA43		MOVLW		.45
				CALL		CALCULOREG
				CALL		SERVO1
				MOVLW		.45
				CALL		CALCULOREG
				CALL		SERVO2
				MOVLW		.45
				CALL		CALCULOREG
				CALL		SERVO3
				MOVLW		.45
				CALL		CALCULOREG
				CALL		SERVO4
				MOVLW		.45
				CALL		CALCULOREG
				CALL		SERVO5
				MOVLW		.45
				CALL		CALCULOREG
				CALL		SERVO6
				MOVLW		.45
				CALL		CALCULOREG
				CALL		SERVO2
				BTFSS		0X53,.0
				GOTO		$+5
				MOVLW		.45
				CALL		CALCULOREG
				CALL		SERVO7
				CLRF		PCLATH
				RETURN		
				MOVLW		.45
				CALL		CALCULOREG
				CALL		SERVO7
				CLRF		PCLATH
				RETURN
CASILLA44		MOVLW		.45
				CALL		CALCULOREG
				CALL		SERVO1
				MOVLW		.45
				CALL		CALCULOREG
				CALL		SERVO2
				MOVLW		.45
				CALL		CALCULOREG
				CALL		SERVO3
				MOVLW		.45
				CALL		CALCULOREG
				CALL		SERVO4
				MOVLW		.45
				CALL		CALCULOREG
				CALL		SERVO5
				MOVLW		.45
				CALL		CALCULOREG
				CALL		SERVO6
				MOVLW		.45
				CALL		CALCULOREG
				CALL		SERVO2
				BTFSS		0X53,.0
				GOTO		$+5
				MOVLW		.45
				CALL		CALCULOREG
				CALL		SERVO7
				CLRF		PCLATH
				RETURN		
				MOVLW		.45
				CALL		CALCULOREG
				CALL		SERVO7
				CLRF		PCLATH
				RETURN
CASILLA45		MOVLW		.45
				CALL		CALCULOREG
				CALL		SERVO1
				MOVLW		.45
				CALL		CALCULOREG
				CALL		SERVO2
				MOVLW		.45
				CALL		CALCULOREG
				CALL		SERVO3
				MOVLW		.45
				CALL		CALCULOREG
				CALL		SERVO4
				MOVLW		.45
				CALL		CALCULOREG
				CALL		SERVO5
				MOVLW		.45
				CALL		CALCULOREG
				CALL		SERVO6
				MOVLW		.45
				CALL		CALCULOREG
				CALL		SERVO2
				BTFSS		0X53,.0
				GOTO		$+5
				MOVLW		.45
				CALL		CALCULOREG
				CALL		SERVO7
				CLRF		PCLATH
				RETURN		
				MOVLW		.45
				CALL		CALCULOREG
				CALL		SERVO7
				CLRF		PCLATH
				RETURN
CASILLA46		MOVLW		.45
				CALL		CALCULOREG
				CALL		SERVO1
				MOVLW		.45
				CALL		CALCULOREG
				CALL		SERVO2
				MOVLW		.45
				CALL		CALCULOREG
				CALL		SERVO3
				MOVLW		.45
				CALL		CALCULOREG
				CALL		SERVO4
				MOVLW		.45
				CALL		CALCULOREG
				CALL		SERVO5
				MOVLW		.45
				CALL		CALCULOREG
				CALL		SERVO6
				MOVLW		.45
				CALL		CALCULOREG
				CALL		SERVO2
				BTFSS		0X53,.0
				GOTO		$+5
				MOVLW		.45
				CALL		CALCULOREG
				CALL		SERVO7
				CLRF		PCLATH
				RETURN		
				MOVLW		.45
				CALL		CALCULOREG
				CALL		SERVO7
				CLRF		PCLATH
				RETURN
CASILLA47		MOVLW		.45
				CALL		CALCULOREG
				CALL		SERVO1
				MOVLW		.45
				CALL		CALCULOREG
				CALL		SERVO2
				MOVLW		.45
				CALL		CALCULOREG
				CALL		SERVO3
				MOVLW		.45
				CALL		CALCULOREG
				CALL		SERVO4
				MOVLW		.45
				CALL		CALCULOREG
				CALL		SERVO5
				MOVLW		.45
				CALL		CALCULOREG
				CALL		SERVO6
				MOVLW		.45
				CALL		CALCULOREG
				CALL		SERVO2
				BTFSS		0X53,.0
				GOTO		$+5
				MOVLW		.45
				CALL		CALCULOREG
				CALL		SERVO7
				CLRF		PCLATH
				RETURN		
				MOVLW		.45
				CALL		CALCULOREG
				CALL		SERVO7
				CLRF		PCLATH
				RETURN
CASILLA48		MOVLW		.45
				CALL		CALCULOREG
				CALL		SERVO1
				MOVLW		.45
				CALL		CALCULOREG
				CALL		SERVO2
				MOVLW		.45
				CALL		CALCULOREG
				CALL		SERVO3
				MOVLW		.45
				CALL		CALCULOREG
				CALL		SERVO4
				MOVLW		.45
				CALL		CALCULOREG
				CALL		SERVO5
				MOVLW		.45
				CALL		CALCULOREG
				CALL		SERVO6
				MOVLW		.45
				CALL		CALCULOREG
				CALL		SERVO2
				BTFSS		0X53,.0
				GOTO		$+5
				MOVLW		.45
				CALL		CALCULOREG
				CALL		SERVO7
				CLRF		PCLATH
				RETURN		
				MOVLW		.45
				CALL		CALCULOREG
				CALL		SERVO7
				CLRF		PCLATH
				RETURN
CASILLA49		MOVLW		.45
				CALL		CALCULOREG
				CALL		SERVO1
				MOVLW		.45
				CALL		CALCULOREG
				CALL		SERVO2
				MOVLW		.45
				CALL		CALCULOREG
				CALL		SERVO3
				MOVLW		.45
				CALL		CALCULOREG
				CALL		SERVO4
				MOVLW		.45
				CALL		CALCULOREG
				CALL		SERVO5
				MOVLW		.45
				CALL		CALCULOREG
				CALL		SERVO6
				MOVLW		.45
				CALL		CALCULOREG
				CALL		SERVO2
				BTFSS		0X53,.0
				GOTO		$+5
				MOVLW		.45
				CALL		CALCULOREG
				CALL		SERVO7
				CLRF		PCLATH
				RETURN		
				MOVLW		.45
				CALL		CALCULOREG
				CALL		SERVO7
				CLRF		PCLATH
				RETURN
CASILLA50		MOVLW		.45
				CALL		CALCULOREG
				CALL		SERVO1
				MOVLW		.45
				CALL		CALCULOREG
				CALL		SERVO2
				MOVLW		.45
				CALL		CALCULOREG
				CALL		SERVO3
				MOVLW		.45
				CALL		CALCULOREG
				CALL		SERVO4
				MOVLW		.45
				CALL		CALCULOREG
				CALL		SERVO5
				MOVLW		.45
				CALL		CALCULOREG
				CALL		SERVO6
				MOVLW		.45
				CALL		CALCULOREG
				CALL		SERVO2
				BTFSS		0X53,.0
				GOTO		$+5
				MOVLW		.45
				CALL		CALCULOREG
				CALL		SERVO7
				CLRF		PCLATH
				RETURN		
				MOVLW		.45
				CALL		CALCULOREG
				CALL		SERVO7
				CLRF		PCLATH
				RETURN
CASILLA51		MOVLW		.45
				CALL		CALCULOREG
				CALL		SERVO1
				MOVLW		.45
				CALL		CALCULOREG
				CALL		SERVO2
				MOVLW		.45
				CALL		CALCULOREG
				CALL		SERVO3
				MOVLW		.45
				CALL		CALCULOREG
				CALL		SERVO4
				MOVLW		.45
				CALL		CALCULOREG
				CALL		SERVO5
				MOVLW		.45
				CALL		CALCULOREG
				CALL		SERVO6
				MOVLW		.45
				CALL		CALCULOREG
				CALL		SERVO2
				BTFSS		0X53,.0
				GOTO		$+5
				MOVLW		.45
				CALL		CALCULOREG
				CALL		SERVO7
				CLRF		PCLATH
				RETURN		
				MOVLW		.45
				CALL		CALCULOREG
				CALL		SERVO7
				CLRF		PCLATH
				RETURN
CASILLA52		MOVLW		.45
				CALL		CALCULOREG
				CALL		SERVO1
				MOVLW		.45
				CALL		CALCULOREG
				CALL		SERVO2
				MOVLW		.45
				CALL		CALCULOREG
				CALL		SERVO3
				MOVLW		.45
				CALL		CALCULOREG
				CALL		SERVO4
				MOVLW		.45
				CALL		CALCULOREG
				CALL		SERVO5
				MOVLW		.45
				CALL		CALCULOREG
				CALL		SERVO6
				MOVLW		.45
				CALL		CALCULOREG
				CALL		SERVO2
				BTFSS		0X53,.0
				GOTO		$+5
				MOVLW		.45
				CALL		CALCULOREG
				CALL		SERVO7
				CLRF		PCLATH
				RETURN		
				MOVLW		.45
				CALL		CALCULOREG
				CALL		SERVO7
				CLRF		PCLATH
				RETURN
CASILLA53		MOVLW		.45
				CALL		CALCULOREG
				CALL		SERVO1
				MOVLW		.45
				CALL		CALCULOREG
				CALL		SERVO2
				MOVLW		.45
				CALL		CALCULOREG
				CALL		SERVO3
				MOVLW		.45
				CALL		CALCULOREG
				CALL		SERVO4
				MOVLW		.45
				CALL		CALCULOREG
				CALL		SERVO5
				MOVLW		.45
				CALL		CALCULOREG
				CALL		SERVO6
				MOVLW		.45
				CALL		CALCULOREG
				CALL		SERVO2
				BTFSS		0X53,.0
				GOTO		$+5
				MOVLW		.45
				CALL		CALCULOREG
				CALL		SERVO7
				CLRF		PCLATH
				RETURN		
				MOVLW		.45
				CALL		CALCULOREG
				CALL		SERVO7
				CLRF		PCLATH
				RETURN
CASILLA54		MOVLW		.45
				CALL		CALCULOREG
				CALL		SERVO1
				MOVLW		.45
				CALL		CALCULOREG
				CALL		SERVO2
				MOVLW		.45
				CALL		CALCULOREG
				CALL		SERVO3
				MOVLW		.45
				CALL		CALCULOREG
				CALL		SERVO4
				MOVLW		.45
				CALL		CALCULOREG
				CALL		SERVO5
				MOVLW		.45
				CALL		CALCULOREG
				CALL		SERVO6
				MOVLW		.45
				CALL		CALCULOREG
				CALL		SERVO2
				BTFSS		0X53,.0
				GOTO		$+5
				MOVLW		.45
				CALL		CALCULOREG
				CALL		SERVO7
				CLRF		PCLATH
				RETURN		
				MOVLW		.45
				CALL		CALCULOREG
				CALL		SERVO7
				CLRF		PCLATH
				RETURN
CASILLA55		MOVLW		.45
				CALL		CALCULOREG
				CALL		SERVO1
				MOVLW		.45
				CALL		CALCULOREG
				CALL		SERVO2
				MOVLW		.45
				CALL		CALCULOREG
				CALL		SERVO3
				MOVLW		.45
				CALL		CALCULOREG
				CALL		SERVO4
				MOVLW		.45
				CALL		CALCULOREG
				CALL		SERVO5
				MOVLW		.45
				CALL		CALCULOREG
				CALL		SERVO6
				MOVLW		.45
				CALL		CALCULOREG
				CALL		SERVO2
				BTFSS		0X53,.0
				GOTO		$+5
				MOVLW		.45
				CALL		CALCULOREG
				CALL		SERVO7
				CLRF		PCLATH
				RETURN		
				MOVLW		.45
				CALL		CALCULOREG
				CALL		SERVO7
				CLRF		PCLATH
				RETURN
CASILLA56		MOVLW		.45
				CALL		CALCULOREG
				CALL		SERVO1
				MOVLW		.45
				CALL		CALCULOREG
				CALL		SERVO2
				MOVLW		.45
				CALL		CALCULOREG
				CALL		SERVO3
				MOVLW		.45
				CALL		CALCULOREG
				CALL		SERVO4
				MOVLW		.45
				CALL		CALCULOREG
				CALL		SERVO5
				MOVLW		.45
				CALL		CALCULOREG
				CALL		SERVO6
				MOVLW		.45
				CALL		CALCULOREG
				CALL		SERVO2
				BTFSS		0X53,.0
				GOTO		$+5
				MOVLW		.45
				CALL		CALCULOREG
				CALL		SERVO7
				CLRF		PCLATH
				RETURN		
				MOVLW		.45
				CALL		CALCULOREG
				CALL		SERVO7
				CLRF		PCLATH
				RETURN
CASILLA57		MOVLW		.45
				CALL		CALCULOREG
				CALL		SERVO1
				MOVLW		.45
				CALL		CALCULOREG
				CALL		SERVO2
				MOVLW		.45
				CALL		CALCULOREG
				CALL		SERVO3
				MOVLW		.45
				CALL		CALCULOREG
				CALL		SERVO4
				MOVLW		.45
				CALL		CALCULOREG
				CALL		SERVO5
				MOVLW		.45
				CALL		CALCULOREG
				CALL		SERVO6
				MOVLW		.45
				CALL		CALCULOREG
				CALL		SERVO2
				BTFSS		0X53,.0
				GOTO		$+5
				MOVLW		.45
				CALL		CALCULOREG
				CALL		SERVO7
				CLRF		PCLATH
				RETURN		
				MOVLW		.45
				CALL		CALCULOREG
				CALL		SERVO7
				CLRF		PCLATH
				RETURN
CASILLA58		MOVLW		.45
				CALL		CALCULOREG
				CALL		SERVO1
				MOVLW		.45
				CALL		CALCULOREG
				CALL		SERVO2
				MOVLW		.45
				CALL		CALCULOREG
				CALL		SERVO3
				MOVLW		.45
				CALL		CALCULOREG
				CALL		SERVO4
				MOVLW		.45
				CALL		CALCULOREG
				CALL		SERVO5
				MOVLW		.45
				CALL		CALCULOREG
				CALL		SERVO6
				MOVLW		.45
				CALL		CALCULOREG
				CALL		SERVO2
				BTFSS		0X53,.0
				GOTO		$+5
				MOVLW		.45
				CALL		CALCULOREG
				CALL		SERVO7
				CLRF		PCLATH
				RETURN		
				MOVLW		.45
				CALL		CALCULOREG
				CALL		SERVO7
				CLRF		PCLATH
				RETURN
CASILLA59		MOVLW		.45
				CALL		CALCULOREG
				CALL		SERVO1
				MOVLW		.45
				CALL		CALCULOREG
				CALL		SERVO2
				MOVLW		.45
				CALL		CALCULOREG
				CALL		SERVO3
				MOVLW		.45
				CALL		CALCULOREG
				CALL		SERVO4
				MOVLW		.45
				CALL		CALCULOREG
				CALL		SERVO5
				MOVLW		.45
				CALL		CALCULOREG
				CALL		SERVO6
				MOVLW		.45
				CALL		CALCULOREG
				CALL		SERVO2
				BTFSS		0X53,.0
				GOTO		$+5
				MOVLW		.45
				CALL		CALCULOREG
				CALL		SERVO7
				CLRF		PCLATH
				RETURN		
				MOVLW		.45
				CALL		CALCULOREG
				CALL		SERVO7
				CLRF		PCLATH
				RETURN
CASILLA60		MOVLW		.45
				CALL		CALCULOREG
				CALL		SERVO1
				MOVLW		.45
				CALL		CALCULOREG
				CALL		SERVO2
				MOVLW		.45
				CALL		CALCULOREG
				CALL		SERVO3
				MOVLW		.45
				CALL		CALCULOREG
				CALL		SERVO4
				MOVLW		.45
				CALL		CALCULOREG
				CALL		SERVO5
				MOVLW		.45
				CALL		CALCULOREG
				CALL		SERVO6
				MOVLW		.45
				CALL		CALCULOREG
				CALL		SERVO2
				BTFSS		0X53,.0
				GOTO		$+5
				MOVLW		.45
				CALL		CALCULOREG
				CALL		SERVO7
				CLRF		PCLATH
				RETURN		
				MOVLW		.45
				CALL		CALCULOREG
				CALL		SERVO7
				CLRF		PCLATH
				RETURN
CASILLA61		MOVLW		.45
				CALL		CALCULOREG
				CALL		SERVO1
				MOVLW		.45
				CALL		CALCULOREG
				CALL		SERVO2
				MOVLW		.45
				CALL		CALCULOREG
				CALL		SERVO3
				MOVLW		.45
				CALL		CALCULOREG
				CALL		SERVO4
				MOVLW		.45
				CALL		CALCULOREG
				CALL		SERVO5
				MOVLW		.45
				CALL		CALCULOREG
				CALL		SERVO6
				MOVLW		.45
				CALL		CALCULOREG
				CALL		SERVO2
				BTFSS		0X53,.0
				GOTO		$+5
				MOVLW		.45
				CALL		CALCULOREG
				CALL		SERVO7
				CLRF		PCLATH
				RETURN		
				MOVLW		.45
				CALL		CALCULOREG
				CALL		SERVO7
				CLRF		PCLATH
				RETURN
CASILLA62		MOVLW		.45
				CALL		CALCULOREG
				CALL		SERVO1
				MOVLW		.45
				CALL		CALCULOREG
				CALL		SERVO2
				MOVLW		.45
				CALL		CALCULOREG
				CALL		SERVO3
				MOVLW		.45
				CALL		CALCULOREG
				CALL		SERVO4
				MOVLW		.45
				CALL		CALCULOREG
				CALL		SERVO5
				MOVLW		.45
				CALL		CALCULOREG
				CALL		SERVO6
				MOVLW		.45
				CALL		CALCULOREG
				CALL		SERVO2
				BTFSS		0X53,.0
				GOTO		$+5
				MOVLW		.45
				CALL		CALCULOREG
				CALL		SERVO7
				CLRF		PCLATH
				RETURN		
				MOVLW		.45
				CALL		CALCULOREG
				CALL		SERVO7
				CLRF		PCLATH
				RETURN
CASILLA63		MOVLW		.45
				CALL		CALCULOREG
				CALL		SERVO1
				MOVLW		.45
				CALL		CALCULOREG
				CALL		SERVO2
				MOVLW		.45
				CALL		CALCULOREG
				CALL		SERVO3
				MOVLW		.45
				CALL		CALCULOREG
				CALL		SERVO4
				MOVLW		.45
				CALL		CALCULOREG
				CALL		SERVO5
				MOVLW		.45
				CALL		CALCULOREG
				CALL		SERVO6
				MOVLW		.45
				CALL		CALCULOREG
				CALL		SERVO2
				BTFSS		0X53,.0
				GOTO		$+5
				MOVLW		.45
				CALL		CALCULOREG
				CALL		SERVO7
				CLRF		PCLATH
				RETURN		
				MOVLW		.45
				CALL		CALCULOREG
				CALL		SERVO7
				CLRF		PCLATH
				RETURN
CASILLA64		MOVLW		.45
				CALL		CALCULOREG
				CALL		SERVO1
				MOVLW		.45
				CALL		CALCULOREG
				CALL		SERVO2
				MOVLW		.45
				CALL		CALCULOREG
				CALL		SERVO3
				MOVLW		.45
				CALL		CALCULOREG
				CALL		SERVO4
				MOVLW		.45
				CALL		CALCULOREG
				CALL		SERVO5
				MOVLW		.45
				CALL		CALCULOREG
				CALL		SERVO6
				MOVLW		.45
				CALL		CALCULOREG
				CALL		SERVO2
				BTFSS		0X53,.0
				GOTO		$+5
				MOVLW		.45
				CALL		CALCULOREG
				CALL		SERVO7
				CLRF		PCLATH
				RETURN		
				MOVLW		.45
				CALL		CALCULOREG
				CALL		SERVO7
				CLRF		PCLATH
				RETURN
			

;****************************SERVOS************************************************
SERVO1			MOVLW		0X21
				MOVWF		0X34
				BSF			PORTB,.0
				CALL		TIEMPOALTO
				BCF			PORTB,.0
				CALL		TIEMPOBAJO
				DECFSZ		0X30
				GOTO		$-5
				RETURN
SERVO2			MOVLW		0X21
				MOVWF		0X34
				BSF			PORTB,.1
				CALL		TIEMPOALTO
				BCF			PORTB,.1
				CALL		TIEMPOBAJO
				DECFSZ		0X30
				GOTO		$-5
				RETURN
SERVO3			MOVLW		0X21
				MOVWF		0X34
				BSF			PORTB,.2
				CALL		TIEMPOALTO
				BCF			PORTB,.2
				CALL		TIEMPOBAJO
				DECFSZ		0X30
				GOTO		$-5
				RETURN
SERVO4			MOVLW		0X21
				MOVWF		0X34
				BSF			PORTB,.3
				CALL		TIEMPOALTO
				BCF			PORTB,.3
				CALL		TIEMPOBAJO
				DECFSZ		0X30
				GOTO		$-5
				RETURN
SERVO5			MOVLW		0X21
				MOVWF		0X34
				BSF			PORTB,.4
				CALL		TIEMPOALTO
				BCF			PORTB,.4
				CALL		TIEMPOBAJO
				DECFSZ		0X30
				GOTO		$-5
				RETURN
SERVO6			MOVLW		0X21
				MOVWF		0X34
				BSF			PORTB,.5
				CALL		TIEMPOALTO
				BCF			PORTB,.5
				CALL		TIEMPOBAJO
				DECFSZ		0X30
				GOTO		$-5
				RETURN
SERVO7			MOVLW		0X21
				MOVWF		0X34
				BSF			PORTB,.6
				CALL		TIEMPOALTO
				BCF			PORTB,.6
				CALL		TIEMPOBAJO
				DECFSZ		0X30
				GOTO		$-5
				RETURN
CALCULOREG		MOVF		0X40,W
				CALL		TABLA_0X30
				MOVWF		0X30
				MOVF		0X40,W
				CALL		TABLA_0X31
				MOVWF		0X31
				MOVF		0X40,W
				CALL		TABLA_0X32
				MOVWF		0X32
				MOVF		0X40,W
				CALL		TABLA_0X33
				MOVWF		0X33
				RETURN	

TIEMPOALTO		MOVF		0X30,W
				MOVWF		0X61
				MOVF		0X31,W
				MOVWF		0X62
				CALL		ST2V_
				RETURN

TIEMPOBAJO		MOVF		0X32,W
				MOVWF		0X61
				MOVF		0X33,W
				MOVWF		0X62
				CALL		ST2V_
				RETURN
				INCLUDE		<TABLAS.ASM>
;}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}
ST2V_:			MOVF		0X62,W
				MOVWF		0X63
DECRE2V_		NOP
                NOP
                NOP
                DECFSZ      0X63,F
                GOTO        DECRE2V_
				DECFSZ		0X61,F
				GOTO		ST2V_
                RETURN
     			END 